/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/usr/local/Cellar/nim/0.17.2/nim/lib -o /Users/johnlindsay/Documents/programming/nimCode/wb_denoise/nimcache/array_2d.o /Users/johnlindsay/Documents/programming/nimCode/wb_denoise/nimcache/array_2d.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Array2D_HHfBYSyyW9bPhznQkAiILyQ tyObject_Array2D_HHfBYSyyW9bPhznQkAiILyQ;
typedef struct tyObject_Vector3_RMaZxokloMCoinSnTL2X1w tyObject_Vector3_RMaZxokloMCoinSnTL2X1w;
typedef struct tySequence_6Ufurnv2NCYPq9bSRr7e5rQ tySequence_6Ufurnv2NCYPq9bSRr7e5rQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TGenericSeq TGenericSeq;
struct tyObject_Vector3_RMaZxokloMCoinSnTL2X1w {
NF a;
NF b;
NF c;
};
struct tyObject_Array2D_HHfBYSyyW9bPhznQkAiILyQ {
NI rows;
NI columns;
tyObject_Vector3_RMaZxokloMCoinSnTL2X1w nodata;
tySequence_6Ufurnv2NCYPq9bSRr7e5rQ* values;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct tySequence_6Ufurnv2NCYPq9bSRr7e5rQ {
  TGenericSeq Sup;
  tyObject_Vector3_RMaZxokloMCoinSnTL2X1w data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_tySequence_6Ufurnv2NCYPq9bSRr7e5rQ)(void* p, NI op);
N_NIMCALL(tySequence_6Ufurnv2NCYPq9bSRr7e5rQ*, repeat_6gkx9aUVkbiN1A9adkuyLMbg)(tyObject_Vector3_RMaZxokloMCoinSnTL2X1w* x, NI n);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
TNimType NTI_HHfBYSyyW9bPhznQkAiILyQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_RMaZxokloMCoinSnTL2X1w_;
TNimType NTI_6Ufurnv2NCYPq9bSRr7e5rQ_;
static N_NIMCALL(void, Marker_tySequence_6Ufurnv2NCYPq9bSRr7e5rQ)(void* p, NI op) {
	tySequence_6Ufurnv2NCYPq9bSRr7e5rQ* a;
	NI T1_;
	a = (tySequence_6Ufurnv2NCYPq9bSRr7e5rQ*)p;
	T1_ = (NI)0;
}

N_NIMCALL(void, newArray2D_G9bUAKWJdYvg7q77gcb9bI2Q)(NI rows, NI columns, tyObject_Vector3_RMaZxokloMCoinSnTL2X1w* initialValue, tyObject_Vector3_RMaZxokloMCoinSnTL2X1w* nodata, tyObject_Array2D_HHfBYSyyW9bPhznQkAiILyQ* Result) {
	(*Result).columns = columns;
	(*Result).rows = rows;
	(*Result).nodata = (*nodata);
	unsureAsgnRef((void**) (&(*Result).values), repeat_6gkx9aUVkbiN1A9adkuyLMbg(initialValue, ((NI) ((NI)(rows * columns)))));
}
NIM_EXTERNC N_NOINLINE(void, unknown_array_2dInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_array_2dDatInit000)(void) {
static TNimNode* TM_Uh9aIdlFEs4VbpoySmmJ02g_2[4];
static TNimNode TM_Uh9aIdlFEs4VbpoySmmJ02g_0[5];
NTI_HHfBYSyyW9bPhznQkAiILyQ_.size = sizeof(tyObject_Array2D_HHfBYSyyW9bPhznQkAiILyQ);
NTI_HHfBYSyyW9bPhznQkAiILyQ_.kind = 18;
NTI_HHfBYSyyW9bPhznQkAiILyQ_.base = 0;
NTI_HHfBYSyyW9bPhznQkAiILyQ_.flags = 2;
TM_Uh9aIdlFEs4VbpoySmmJ02g_2[0] = &TM_Uh9aIdlFEs4VbpoySmmJ02g_0[1];
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[1].kind = 1;
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[1].offset = offsetof(tyObject_Array2D_HHfBYSyyW9bPhznQkAiILyQ, rows);
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[1].name = "rows";
TM_Uh9aIdlFEs4VbpoySmmJ02g_2[1] = &TM_Uh9aIdlFEs4VbpoySmmJ02g_0[2];
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[2].kind = 1;
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[2].offset = offsetof(tyObject_Array2D_HHfBYSyyW9bPhznQkAiILyQ, columns);
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[2].name = "columns";
TM_Uh9aIdlFEs4VbpoySmmJ02g_2[2] = &TM_Uh9aIdlFEs4VbpoySmmJ02g_0[3];
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[3].kind = 1;
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[3].offset = offsetof(tyObject_Array2D_HHfBYSyyW9bPhznQkAiILyQ, nodata);
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[3].typ = (&NTI_RMaZxokloMCoinSnTL2X1w_);
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[3].name = "nodata";
TM_Uh9aIdlFEs4VbpoySmmJ02g_2[3] = &TM_Uh9aIdlFEs4VbpoySmmJ02g_0[4];
NTI_6Ufurnv2NCYPq9bSRr7e5rQ_.size = sizeof(tySequence_6Ufurnv2NCYPq9bSRr7e5rQ*);
NTI_6Ufurnv2NCYPq9bSRr7e5rQ_.kind = 24;
NTI_6Ufurnv2NCYPq9bSRr7e5rQ_.base = (&NTI_RMaZxokloMCoinSnTL2X1w_);
NTI_6Ufurnv2NCYPq9bSRr7e5rQ_.flags = 2;
NTI_6Ufurnv2NCYPq9bSRr7e5rQ_.marker = Marker_tySequence_6Ufurnv2NCYPq9bSRr7e5rQ;
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[4].kind = 1;
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[4].offset = offsetof(tyObject_Array2D_HHfBYSyyW9bPhznQkAiILyQ, values);
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[4].typ = (&NTI_6Ufurnv2NCYPq9bSRr7e5rQ_);
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[4].name = "values";
TM_Uh9aIdlFEs4VbpoySmmJ02g_0[0].len = 4; TM_Uh9aIdlFEs4VbpoySmmJ02g_0[0].kind = 2; TM_Uh9aIdlFEs4VbpoySmmJ02g_0[0].sons = &TM_Uh9aIdlFEs4VbpoySmmJ02g_2[0];
NTI_HHfBYSyyW9bPhznQkAiILyQ_.node = &TM_Uh9aIdlFEs4VbpoySmmJ02g_0[0];
}

