/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/usr/local/Cellar/nim/0.17.2/nim/lib -o /Users/johnlindsay/Documents/programming/nimCode/wb_denoise/nimcache/byte_order_reader.o /Users/johnlindsay/Documents/programming/nimCode/wb_denoise/nimcache/byte_order_reader.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_6H5Oh5UUvVCLiakt9aTwtUQ tySequence_6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NU8 tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw;
struct tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ {
tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* data;
tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw endian;
NI pos;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tySequence_6H5Oh5UUvVCLiakt9aTwtUQ {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
extern TNimType NTI_6H5Oh5UUvVCLiakt9aTwtUQ_;

N_NIMCALL(void, newByteOrderReader_wBmQ8d88r4Ig3UfUSerbWg)(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* data, tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw endian, NI pos, tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ* Result) {
	tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ T1_;
	memset((void*)(&T1_), 0, sizeof(T1_));
	memset((void*)(&T1_), 0, sizeof(T1_));
	genericSeqAssign((&T1_.data), data, (&NTI_6H5Oh5UUvVCLiakt9aTwtUQ_));
	T1_.endian = endian;
	T1_.pos = pos;
	unsureAsgnRef((void**) (&(*Result).data), T1_.data);
	(*Result).endian = T1_.endian;
	(*Result).pos = T1_.pos;
}
NIM_EXTERNC N_NOINLINE(void, unknown_byte_order_readerInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_byte_order_readerDatInit000)(void) {
}

