/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/usr/local/Cellar/nim/0.17.2/nim/lib -o /Users/johnlindsay/Documents/programming/nimCode/wb_denoise/nimcache/raster.o /Users/johnlindsay/Documents/programming/nimCode/wb_denoise/nimcache/raster.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <setjmp.h>
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_FileIOError_e5YQgQH5C8Fl9cRhRXJezhA tyObject_FileIOError_e5YQgQH5C8Fl9cRhRXJezhA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct TSafePoint TSafePoint;
typedef struct tySequence_6H5Oh5UUvVCLiakt9aTwtUQ tySequence_6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ;
typedef struct tyObject_IndexError_b0IIwghFQBADkB2c86kXQA tyObject_IndexError_b0IIwghFQBADkB2c86kXQA;
typedef struct tyObject_ByteOrderWriter_mZRGtGKlNjXmPT9b8N9avxsA tyObject_ByteOrderWriter_mZRGtGKlNjXmPT9b8N9avxsA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ;
typedef NU8 tyEnum_DataScale_RrPL9cDKg0HP9c6NuFDso29bA;
typedef NU8 tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw;
struct tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ {
NimStringDesc* headerFilename;
NimStringDesc* dataFilename;
NF minimum;
NF maximum;
NI rows;
NI columns;
NI stacks;
NF north;
NF south;
NF east;
NF west;
tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ dataType;
NimStringDesc* zUnits;
NimStringDesc* xyUnits;
NimStringDesc* projection;
tyEnum_DataScale_RrPL9cDKg0HP9c6NuFDso29bA dataScale;
NF displayMinimum;
NF displayMaximum;
NimStringDesc* palette;
NF nodata;
tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw byteOrder;
NF paletteNonlinearity;
NF resolutionX;
NF resolutionY;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* metadata;
tySequence_Zj5xKXgsXnI4n4hPS6nACA* values;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
struct tyObject_FileIOError_e5YQgQH5C8Fl9cRhRXJezhA {
  Exception Sup;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ {
tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* data;
tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw endian;
NI pos;
};
struct tyObject_IndexError_b0IIwghFQBADkB2c86kXQA {
  Exception Sup;
};
typedef NU8 tyEnum_FloatClass_pPga1yW9b8J9cwNnm9b1aPRnA;
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_ByteOrderWriter_mZRGtGKlNjXmPT9b8N9avxsA {
tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* data;
tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw endian;
NI pos;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_6H5Oh5UUvVCLiakt9aTwtUQ {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA)(void* p, NI op);
N_NIMCALL(NIM_BOOL, nsuEndsWith)(NimStringDesc* s, NimStringDesc* suffix);
N_NIMCALL(NimStringDesc*, nsuToLowerAsciiStr)(NimStringDesc* s);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s, NimStringDesc* sub, NimStringDesc* by);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_RLjzwRut8ihej9aDTKbr77Q)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(void, read_ebB70bAWQPd5TX9cPi5HkrQ)(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ* self);
N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, newSeq_9cL6dIz2UWtIh3FeS5x4hxA)(NI len);
N_NIMCALL(FILE*, open_hqzpWQbdA2B8l9a6wwNoP4g)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(NIM_BOOL, readLine_sO1bQXVRA6RP9cdYJXNKeSw)(FILE* f, NimStringDesc** line);
N_NIMCALL(NIM_BOOL, contains_bKoQGynT9bWCEn79aXG8be9aw)(NimStringDesc* s, NimStringDesc* sub);
N_NIMCALL(NF, nsuParseFloat)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw chars);
N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitString)(NimStringDesc* s, NimStringDesc* sep, NI maxsplit);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, newSeq_QEg0mebvlEuej5bmGcaclQ)(NI len);
N_NIMCALL(NI64, nosgetFileSize)(NimStringDesc* file);
N_NIMCALL(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*, newSeq_OVoBJFASw7yjKnQkxoXCzw)(NI len);
N_NIMCALL(NI, readBytes_u45tKTCEtv32o47mnn9cWMg)(FILE* f, NU8* a, NI aLen_0, NI start, NI len);
N_NIMCALL(void, newByteOrderReader_wBmQ8d88r4Ig3UfUSerbWg)(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* data, tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw endian, NI pos, tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ* Result);
N_NOINLINE(void, chckNil)(void* p);
static N_INLINE(NF, readFloat64_Nj9aeK6evnfhHL5m3vUzwYwraster)(tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ* b);
static N_INLINE(void, littleEndian64_IzdisrH4sYnsItUtxSkomAraster)(void* outp, void* inp);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
static N_INLINE(void, bigEndian64_IzdisrH4sYnsItUtxSkomA_2raster)(void* outp, void* inp);
static N_INLINE(void, swapEndian64_IzdisrH4sYnsItUtxSkomA_3raster)(void* outp, void* inp);
static N_INLINE(NF32, readFloat32_iegdcqKF0iRbudzM03sr0Qraster)(tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ* b);
static N_INLINE(void, littleEndian32_IzdisrH4sYnsItUtxSkomA_4raster)(void* outp, void* inp);
static N_INLINE(void, bigEndian32_IzdisrH4sYnsItUtxSkomA_5raster)(void* outp, void* inp);
static N_INLINE(void, swapEndian32_IzdisrH4sYnsItUtxSkomA_6raster)(void* outp, void* inp);
static N_INLINE(NI32, readInt32_YpaWGTN1retCbzXwCs2lYAraster)(tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ* b);
static N_INLINE(NI16, readInt16_HUN2sABaNPqAgLYsUVbbZAraster)(tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ* b);
static N_INLINE(void, littleEndian16_IzdisrH4sYnsItUtxSkomA_7raster)(void* outp, void* inp);
static N_INLINE(void, bigEndian16_IzdisrH4sYnsItUtxSkomA_8raster)(void* outp, void* inp);
static N_INLINE(void, swapEndian16_IzdisrH4sYnsItUtxSkomA_9raster)(void* outp, void* inp);
static N_INLINE(NI8, readInt8_g49bc3QmRiVKJqiOgAd6Hbgraster)(tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ* b);
static N_INLINE(void, popSafePoint)(void);
N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw_2)(FILE* f);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(tyEnum_FloatClass_pPga1yW9b8J9cwNnm9b1aPRnA, classify_rfodLs2J9b87EDgWnWZoObA)(NF x);
N_NIMCALL(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, repeat_pBHAjECB1SlEt8MwweaBAA)(NF x, NI n);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, calculateMinAndMax_UWLXtJXzLzoXimKlJPPcrw)(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ* self);
static N_INLINE(void, writeLine_rBQVO3cm3BhnA9aEFD7PG6Qraster)(FILE* f, NimStringDesc** x, NI xLen_0);
N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
N_NIMCALL(NimStringDesc*, dollar__ecmw559aInnl3DSY6bSGsDA)(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ* self);
N_NIMCALL(NimStringDesc*, nsuFormatVarargs)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_NIMCALL(void, newByteOrderWriter_i9bKyO6VqGAi1lK9cGnNKLZg)(NI size, tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw endian, NI pos, tyObject_ByteOrderWriter_mZRGtGKlNjXmPT9b8N9avxsA* Result);
static N_INLINE(void, writeFloat64_NTvU1iusBzUqugysmVpL0wraster)(tyObject_ByteOrderWriter_mZRGtGKlNjXmPT9b8N9avxsA* b, NF* value);
static N_INLINE(void, writeFloat32_04Wuv1SIlKOZr9cZdef0hZwraster)(tyObject_ByteOrderWriter_mZRGtGKlNjXmPT9b8N9avxsA* b, NF32* value);
static N_INLINE(void, writeInt32_QA2F6NQYDR8mdNGxjEyzcgraster)(tyObject_ByteOrderWriter_mZRGtGKlNjXmPT9b8N9avxsA* b, NI32* value);
static N_INLINE(void, writeInt16_7qbGaWN9amZW9bykPdKTFaUQraster)(tyObject_ByteOrderWriter_mZRGtGKlNjXmPT9b8N9avxsA* b, NI16* value);
static N_INLINE(void, writeInt8_zaZ7wXN15zKjT9akG9c3G76Qraster)(tyObject_ByteOrderWriter_mZRGtGKlNjXmPT9b8N9avxsA* b, NI8* value);
N_NIMCALL(NI, writeBytes_g0nTVLIZgU2QDdGZlYBRPw)(FILE* f, NU8* a, NI aLen_0, NI start, NI len);
static N_INLINE(Exception*, getCurrentException)(void);
N_NIMCALL(NimStringDesc*, reprAny)(void* p, TNimType* typ);
static N_INLINE(NimStringDesc*, getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qraster)(void);
static N_INLINE(void, popCurrentException)(void);
TNimType NTI_QuEIJJ9arZP4gpDlFzlysJQ_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_VeybIFcMcPMXNvVQ9cAA9a9bQ_;
TNimType NTI_RrPL9cDKg0HP9c6NuFDso29bA_;
extern TNimType NTI_0BVYNY0K9cz7BUPI3AnbEQw_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
TNimType NTI_Zj5xKXgsXnI4n4hPS6nACA_;
extern TNimType NTI_bAvOj2UcojKN87yAQLs0aw_;
TNimType NTI_e5YQgQH5C8Fl9cRhRXJezhA_;
TNimType NTI_RLjzwRut8ihej9aDTKbr77Q_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern TNimType NTI_z58cIdR0vOibqJ0QwYvB3Q_;
extern TNimType NTI_b0IIwghFQBADkB2c86kXQA_;
extern Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
extern TNimType NTI_oUKtBcKRdK6usj8RWrlp6A_;
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_9, ".dep", 4);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_10, ".tas", 4);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_11, "Unrecognized file extension", 27);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_13, "min:", 4);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_14, "display", 7);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_15, ":", 1);
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_Y3cCMs4xzyrNE4rsvwdnGQ_16 = {
0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_17, "max:", 4);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_18, "rows:", 5);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_19, "cols:", 5);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_20, "stacks:", 7);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_21, "north:", 6);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_22, "south:", 6);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_23, "east:", 5);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_24, "west:", 5);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_25, "data type:", 10);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_26, "float", 5);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_27, "double", 6);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_28, "i32", 3);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_29, "short", 5);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_30, "integer", 7);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_31, "byte", 4);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_32, "z units:", 8);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_33, "xy units:", 9);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_34, "projection:", 11);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_35, "data scale:", 11);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_36, "continuous", 10);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_37, "categorical", 11);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_38, "bool", 4);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_39, "display min:", 12);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_40, "display max:", 12);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_41, "preferred palette:", 18);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_42, "nodata:", 7);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_43, "LITTLE", 6);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_44, "palette nonlinearity:", 21);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_45, "metadata", 8);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_47, "Read past data length", 21);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_50, "\012", 1);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_51, "Min:\011$1\012", 8);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_52, "Max:\011$1\012", 8);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_53, "Rows:\011$1\012", 9);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_54, "Cols:\011$1\012", 9);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_55, "Stacks:\011$1\012", 11);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_56, "North:\011$1\012", 10);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_57, "South:\011$1\012", 10);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_58, "East:\011$1\012", 9);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_59, "West:\011$1\012", 9);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_60, "Data Type:\011double\012", 18);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_61, "Data Type:\011float\012", 17);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_62, "Data Type:\011i32\012", 15);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_63, "Data Type:\011integer\012", 19);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_64, "Data Type:\011byte\012", 16);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_65, "Z Units:\011$1\012", 12);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_66, "XY Units:\011$1\012", 13);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_67, "Projection:\011$1\012", 15);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_68, "Data Scale:\011$1\012", 15);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_69, "Display Min:\011$1\012", 16);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_70, "Display Max:\011$1\012", 16);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_71, "Preferred Palette:\011$1\012", 22);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_72, "NoData:\011$1\012", 11);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_73, "Byte Order:\011LITTLE_ENDIAN\012", 26);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_74, "Byte Order:\011BIG_ENDIAN\012", 23);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_75, "Palette Nonlinearity:\011$1\012", 25);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_76, "Metadata Entry:\011$1\012", 19);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_77, ";", 1);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_79, "Write past data length", 22);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_80, "Got exception ", 14);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_81, " with message ", 14);
STRING_LITERAL(TM_Y3cCMs4xzyrNE4rsvwdnGQ_82, "", 0);
static N_NIMCALL(void, Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA)(void* p, NI op) {
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* a;
	NI T1_;
	a = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, Marker_tyRef_RLjzwRut8ihej9aDTKbr77Q)(void* p, NI op) {
	tyObject_FileIOError_e5YQgQH5C8Fl9cRhRXJezhA* a;
	a = (tyObject_FileIOError_e5YQgQH5C8Fl9cRhRXJezhA*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.up, op);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, littleEndian64_IzdisrH4sYnsItUtxSkomAraster)(void* outp, void* inp) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(outp, inp, ((NI) 8));
}

static N_INLINE(void, swapEndian64_IzdisrH4sYnsItUtxSkomA_3raster)(void* outp, void* inp) {
	NU64* i;
	NU64* o;
	i = ((NU64*) (inp));
	o = ((NU64*) (outp));
	(*o) = __builtin_bswap64((*i));
}

static N_INLINE(void, bigEndian64_IzdisrH4sYnsItUtxSkomA_2raster)(void* outp, void* inp) {
	swapEndian64_IzdisrH4sYnsItUtxSkomA_3raster(outp, inp);
}

static N_INLINE(NF, readFloat64_Nj9aeK6evnfhHL5m3vUzwYwraster)(tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ* b) {
	NF result;
	result = (NF)0;
	{
		NIM_BOOL T3_;
		NI T4_;
		tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T4_ = ((*b).data ? (*b).data->Sup.len : 0);
		T3_ = (T4_ < (NI)((*b).pos + ((NI) 8)));
		if (T3_) goto LA5_;
		T3_ = ((*b).pos < ((NI) 0));
		LA5_: ;
		if (!T3_) goto LA6_;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
		(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
		T8_ = (NimStringDesc*)0;
		T8_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_47));
		if (T8_) nimGCunrefNoCycle(T8_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "IndexError");
	}
	LA6_: ;
	{
		if (!((*b).endian == ((tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw) 0))) goto LA11_;
		littleEndian64_IzdisrH4sYnsItUtxSkomAraster(((void*) ((&result))), ((void*) ((&(*b).data->data[(*b).pos]))));
	}
	goto LA9_;
	LA11_: ;
	{
		bigEndian64_IzdisrH4sYnsItUtxSkomA_2raster(((void*) ((&result))), ((void*) ((&(*b).data->data[(*b).pos]))));
	}
	LA9_: ;
	(*b).pos += ((NI) 8);
	return result;
}

static N_INLINE(void, littleEndian32_IzdisrH4sYnsItUtxSkomA_4raster)(void* outp, void* inp) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(outp, inp, ((NI) 4));
}

static N_INLINE(void, swapEndian32_IzdisrH4sYnsItUtxSkomA_6raster)(void* outp, void* inp) {
	NU32* i;
	NU32* o;
	i = ((NU32*) (inp));
	o = ((NU32*) (outp));
	(*o) = __builtin_bswap32((*i));
}

static N_INLINE(void, bigEndian32_IzdisrH4sYnsItUtxSkomA_5raster)(void* outp, void* inp) {
	swapEndian32_IzdisrH4sYnsItUtxSkomA_6raster(outp, inp);
}

static N_INLINE(NF32, readFloat32_iegdcqKF0iRbudzM03sr0Qraster)(tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ* b) {
	NF32 result;
	result = (NF32)0;
	{
		NIM_BOOL T3_;
		NI T4_;
		tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T4_ = ((*b).data ? (*b).data->Sup.len : 0);
		T3_ = (T4_ < (NI)((*b).pos + ((NI) 4)));
		if (T3_) goto LA5_;
		T3_ = ((*b).pos < ((NI) 0));
		LA5_: ;
		if (!T3_) goto LA6_;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
		(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
		T8_ = (NimStringDesc*)0;
		T8_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_47));
		if (T8_) nimGCunrefNoCycle(T8_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "IndexError");
	}
	LA6_: ;
	{
		if (!((*b).endian == ((tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw) 0))) goto LA11_;
		littleEndian32_IzdisrH4sYnsItUtxSkomA_4raster(((void*) ((&result))), ((void*) ((&(*b).data->data[(*b).pos]))));
	}
	goto LA9_;
	LA11_: ;
	{
		bigEndian32_IzdisrH4sYnsItUtxSkomA_5raster(((void*) ((&result))), ((void*) ((&(*b).data->data[(*b).pos]))));
	}
	LA9_: ;
	(*b).pos += ((NI) 4);
	return result;
}

static N_INLINE(NI32, readInt32_YpaWGTN1retCbzXwCs2lYAraster)(tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ* b) {
	NI32 result;
	result = (NI32)0;
	{
		NIM_BOOL T3_;
		NI T4_;
		tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T4_ = ((*b).data ? (*b).data->Sup.len : 0);
		T3_ = (T4_ < (NI)((*b).pos + ((NI) 4)));
		if (T3_) goto LA5_;
		T3_ = ((*b).pos < ((NI) 0));
		LA5_: ;
		if (!T3_) goto LA6_;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
		(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
		T8_ = (NimStringDesc*)0;
		T8_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_47));
		if (T8_) nimGCunrefNoCycle(T8_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "IndexError");
	}
	LA6_: ;
	{
		if (!((*b).endian == ((tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw) 0))) goto LA11_;
		littleEndian32_IzdisrH4sYnsItUtxSkomA_4raster(((void*) ((&result))), ((void*) ((&(*b).data->data[(*b).pos]))));
	}
	goto LA9_;
	LA11_: ;
	{
		bigEndian32_IzdisrH4sYnsItUtxSkomA_5raster(((void*) ((&result))), ((void*) ((&(*b).data->data[(*b).pos]))));
	}
	LA9_: ;
	(*b).pos += ((NI) 4);
	return result;
}

static N_INLINE(void, littleEndian16_IzdisrH4sYnsItUtxSkomA_7raster)(void* outp, void* inp) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(outp, inp, ((NI) 2));
}

static N_INLINE(void, swapEndian16_IzdisrH4sYnsItUtxSkomA_9raster)(void* outp, void* inp) {
	NU16* i;
	NU16* o;
	i = ((NU16*) (inp));
	o = ((NU16*) (outp));
	(*o) = __builtin_bswap16((*i));
}

static N_INLINE(void, bigEndian16_IzdisrH4sYnsItUtxSkomA_8raster)(void* outp, void* inp) {
	swapEndian16_IzdisrH4sYnsItUtxSkomA_9raster(outp, inp);
}

static N_INLINE(NI16, readInt16_HUN2sABaNPqAgLYsUVbbZAraster)(tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ* b) {
	NI16 result;
	result = (NI16)0;
	{
		NIM_BOOL T3_;
		NI T4_;
		tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T4_ = ((*b).data ? (*b).data->Sup.len : 0);
		T3_ = (T4_ < (NI)((*b).pos + ((NI) 2)));
		if (T3_) goto LA5_;
		T3_ = ((*b).pos < ((NI) 0));
		LA5_: ;
		if (!T3_) goto LA6_;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
		(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
		T8_ = (NimStringDesc*)0;
		T8_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_47));
		if (T8_) nimGCunrefNoCycle(T8_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "IndexError");
	}
	LA6_: ;
	{
		if (!((*b).endian == ((tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw) 0))) goto LA11_;
		littleEndian16_IzdisrH4sYnsItUtxSkomA_7raster(((void*) ((&result))), ((void*) ((&(*b).data->data[(*b).pos]))));
	}
	goto LA9_;
	LA11_: ;
	{
		bigEndian16_IzdisrH4sYnsItUtxSkomA_8raster(((void*) ((&result))), ((void*) ((&(*b).data->data[(*b).pos]))));
	}
	LA9_: ;
	(*b).pos += ((NI) 2);
	return result;
}

static N_INLINE(NI8, readInt8_g49bc3QmRiVKJqiOgAd6Hbgraster)(tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ* b) {
	NI8 result;
	result = (NI8)0;
	{
		NIM_BOOL T3_;
		NI T4_;
		tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T4_ = ((*b).data ? (*b).data->Sup.len : 0);
		T3_ = (T4_ < (NI)((*b).pos + ((NI) 1)));
		if (T3_) goto LA5_;
		T3_ = ((*b).pos < ((NI) 0));
		LA5_: ;
		if (!T3_) goto LA6_;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
		(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
		T8_ = (NimStringDesc*)0;
		T8_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_47));
		if (T8_) nimGCunrefNoCycle(T8_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "IndexError");
	}
	LA6_: ;
	result = ((NI8) ((*b).data->data[(*b).pos]));
	(*b).pos += ((NI) 1);
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

N_NIMCALL(void, read_ebB70bAWQPd5TX9cPi5HkrQ)(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ* self) {
	FILE* f;
	TSafePoint TM_Y3cCMs4xzyrNE4rsvwdnGQ_12;
	unsureAsgnRef((void**) (&(*self).metadata), newSeq_9cL6dIz2UWtIh3FeS5x4hxA(((NI) 0)));
	f = open_hqzpWQbdA2B8l9a6wwNoP4g((*self).headerFilename, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
	pushSafePoint(&TM_Y3cCMs4xzyrNE4rsvwdnGQ_12);
	TM_Y3cCMs4xzyrNE4rsvwdnGQ_12.status = _setjmp(TM_Y3cCMs4xzyrNE4rsvwdnGQ_12.context);
	if (TM_Y3cCMs4xzyrNE4rsvwdnGQ_12.status == 0) {
		NI64 fileSize;
		tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* buf;
		FILE* df;
		TSafePoint TM_Y3cCMs4xzyrNE4rsvwdnGQ_46;
		{
			NimStringDesc* line;
			NimStringDesc* res;
			line = (NimStringDesc*)0;
			res = rawNewString(((NI) 80));
			{
				while (1) {
					NIM_BOOL T5_;
					NimStringDesc* lcLine;
					T5_ = (NIM_BOOL)0;
					T5_ = readLine_sO1bQXVRA6RP9cdYJXNKeSw(f, (&res));
					if (!T5_) goto LA4;
					line = res;
					lcLine = nsuToLowerAsciiStr(line);
					{
						NIM_BOOL T8_;
						NIM_BOOL T10_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T13_;
						NimStringDesc* T14_;
						T8_ = (NIM_BOOL)0;
						T8_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_13));
						if (!(T8_)) goto LA9_;
						T10_ = (NIM_BOOL)0;
						T10_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_14));
						T8_ = !(T10_);
						LA9_: ;
						if (!T8_) goto LA11_;
						T13_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T13_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T14_ = (NimStringDesc*)0;
						T14_ = nsuStrip(T13_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						(*self).minimum = nsuParseFloat(T14_);
					}
					goto LA6_;
					LA11_: ;
					{
						NIM_BOOL T16_;
						NIM_BOOL T18_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T21_;
						NimStringDesc* T22_;
						T16_ = (NIM_BOOL)0;
						T16_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_17));
						if (!(T16_)) goto LA17_;
						T18_ = (NIM_BOOL)0;
						T18_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_14));
						T16_ = !(T18_);
						LA17_: ;
						if (!T16_) goto LA19_;
						T21_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T21_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T22_ = (NimStringDesc*)0;
						T22_ = nsuStrip(T21_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						(*self).maximum = nsuParseFloat(T22_);
					}
					goto LA6_;
					LA19_: ;
					{
						NIM_BOOL T24_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T27_;
						NimStringDesc* T28_;
						T24_ = (NIM_BOOL)0;
						T24_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_18));
						if (!T24_) goto LA25_;
						T27_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T27_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T28_ = (NimStringDesc*)0;
						T28_ = nsuStrip(T27_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						(*self).rows = nsuParseInt(T28_);
					}
					goto LA6_;
					LA25_: ;
					{
						NIM_BOOL T30_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T33_;
						NimStringDesc* T34_;
						T30_ = (NIM_BOOL)0;
						T30_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_19));
						if (!T30_) goto LA31_;
						T33_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T33_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T34_ = (NimStringDesc*)0;
						T34_ = nsuStrip(T33_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						(*self).columns = nsuParseInt(T34_);
					}
					goto LA6_;
					LA31_: ;
					{
						NIM_BOOL T36_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T39_;
						NimStringDesc* T40_;
						T36_ = (NIM_BOOL)0;
						T36_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_20));
						if (!T36_) goto LA37_;
						T39_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T39_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T40_ = (NimStringDesc*)0;
						T40_ = nsuStrip(T39_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						(*self).stacks = nsuParseInt(T40_);
					}
					goto LA6_;
					LA37_: ;
					{
						NIM_BOOL T42_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T45_;
						NimStringDesc* T46_;
						T42_ = (NIM_BOOL)0;
						T42_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_21));
						if (!T42_) goto LA43_;
						T45_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T45_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T46_ = (NimStringDesc*)0;
						T46_ = nsuStrip(T45_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						(*self).north = nsuParseFloat(T46_);
					}
					goto LA6_;
					LA43_: ;
					{
						NIM_BOOL T48_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T51_;
						NimStringDesc* T52_;
						T48_ = (NIM_BOOL)0;
						T48_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_22));
						if (!T48_) goto LA49_;
						T51_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T51_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T52_ = (NimStringDesc*)0;
						T52_ = nsuStrip(T51_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						(*self).south = nsuParseFloat(T52_);
					}
					goto LA6_;
					LA49_: ;
					{
						NIM_BOOL T54_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T57_;
						NimStringDesc* T58_;
						T54_ = (NIM_BOOL)0;
						T54_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_23));
						if (!T54_) goto LA55_;
						T57_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T57_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T58_ = (NimStringDesc*)0;
						T58_ = nsuStrip(T57_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						(*self).east = nsuParseFloat(T58_);
					}
					goto LA6_;
					LA55_: ;
					{
						NIM_BOOL T60_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T63_;
						NimStringDesc* T64_;
						T60_ = (NIM_BOOL)0;
						T60_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_24));
						if (!T60_) goto LA61_;
						T63_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T63_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T64_ = (NimStringDesc*)0;
						T64_ = nsuStrip(T63_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						(*self).west = nsuParseFloat(T64_);
					}
					goto LA6_;
					LA61_: ;
					{
						NIM_BOOL T66_;
						NimStringDesc* v;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T69_;
						NimStringDesc* T70_;
						T66_ = (NIM_BOOL)0;
						T66_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_25));
						if (!T66_) goto LA67_;
						T69_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T69_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T70_ = (NimStringDesc*)0;
						T70_ = nsuStrip(T69_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						v = nsuToLowerAsciiStr(T70_);
						{
							NIM_BOOL T73_;
							T73_ = (NIM_BOOL)0;
							T73_ = contains_bKoQGynT9bWCEn79aXG8be9aw(v, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_26));
							if (!T73_) goto LA74_;
							(*self).dataType = ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 1);
						}
						goto LA71_;
						LA74_: ;
						{
							NIM_BOOL T77_;
							T77_ = (NIM_BOOL)0;
							T77_ = contains_bKoQGynT9bWCEn79aXG8be9aw(v, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_27));
							if (!T77_) goto LA78_;
							(*self).dataType = ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 0);
						}
						goto LA71_;
						LA78_: ;
						{
							NIM_BOOL T81_;
							T81_ = (NIM_BOOL)0;
							T81_ = contains_bKoQGynT9bWCEn79aXG8be9aw(v, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_28));
							if (!T81_) goto LA82_;
							(*self).dataType = ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 2);
						}
						goto LA71_;
						LA82_: ;
						{
							NIM_BOOL T85_;
							T85_ = (NIM_BOOL)0;
							T85_ = contains_bKoQGynT9bWCEn79aXG8be9aw(v, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_29));
							if (T85_) goto LA86_;
							T85_ = contains_bKoQGynT9bWCEn79aXG8be9aw(v, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_30));
							LA86_: ;
							if (!T85_) goto LA87_;
							(*self).dataType = ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 3);
						}
						goto LA71_;
						LA87_: ;
						{
							NIM_BOOL T90_;
							T90_ = (NIM_BOOL)0;
							T90_ = contains_bKoQGynT9bWCEn79aXG8be9aw(v, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_31));
							if (!T90_) goto LA91_;
							(*self).dataType = ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 4);
						}
						goto LA71_;
						LA91_: ;
						LA71_: ;
					}
					goto LA6_;
					LA67_: ;
					{
						NIM_BOOL T94_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T97_;
						T94_ = (NIM_BOOL)0;
						T94_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_32));
						if (!T94_) goto LA95_;
						T97_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T97_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						unsureAsgnRef((void**) (&(*self).zUnits), nsuStrip(T97_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16));
					}
					goto LA6_;
					LA95_: ;
					{
						NIM_BOOL T99_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T102_;
						T99_ = (NIM_BOOL)0;
						T99_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_33));
						if (!T99_) goto LA100_;
						T102_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T102_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						unsureAsgnRef((void**) (&(*self).xyUnits), nsuStrip(T102_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16));
					}
					goto LA6_;
					LA100_: ;
					{
						NIM_BOOL T104_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T107_;
						T104_ = (NIM_BOOL)0;
						T104_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_34));
						if (!T104_) goto LA105_;
						T107_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T107_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						unsureAsgnRef((void**) (&(*self).projection), nsuStrip(T107_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16));
					}
					goto LA6_;
					LA105_: ;
					{
						NIM_BOOL T109_;
						NimStringDesc* v_2;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T112_;
						NimStringDesc* T113_;
						T109_ = (NIM_BOOL)0;
						T109_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_35));
						if (!T109_) goto LA110_;
						T112_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T112_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T113_ = (NimStringDesc*)0;
						T113_ = nsuStrip(T112_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						v_2 = nsuToLowerAsciiStr(T113_);
						{
							NIM_BOOL T116_;
							T116_ = (NIM_BOOL)0;
							T116_ = contains_bKoQGynT9bWCEn79aXG8be9aw(v_2, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_36));
							if (!T116_) goto LA117_;
							(*self).dataScale = ((tyEnum_DataScale_RrPL9cDKg0HP9c6NuFDso29bA) 0);
						}
						goto LA114_;
						LA117_: ;
						{
							NIM_BOOL T120_;
							T120_ = (NIM_BOOL)0;
							T120_ = contains_bKoQGynT9bWCEn79aXG8be9aw(v_2, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_37));
							if (!T120_) goto LA121_;
							(*self).dataScale = ((tyEnum_DataScale_RrPL9cDKg0HP9c6NuFDso29bA) 1);
						}
						goto LA114_;
						LA121_: ;
						{
							NIM_BOOL T124_;
							T124_ = (NIM_BOOL)0;
							T124_ = contains_bKoQGynT9bWCEn79aXG8be9aw(v_2, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_38));
							if (!T124_) goto LA125_;
							(*self).dataScale = ((tyEnum_DataScale_RrPL9cDKg0HP9c6NuFDso29bA) 2);
						}
						goto LA114_;
						LA125_: ;
						LA114_: ;
					}
					goto LA6_;
					LA110_: ;
					{
						NIM_BOOL T128_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T131_;
						NimStringDesc* T132_;
						T128_ = (NIM_BOOL)0;
						T128_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_39));
						if (!T128_) goto LA129_;
						T131_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T131_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T132_ = (NimStringDesc*)0;
						T132_ = nsuStrip(T131_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						(*self).displayMinimum = nsuParseFloat(T132_);
					}
					goto LA6_;
					LA129_: ;
					{
						NIM_BOOL T134_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T137_;
						NimStringDesc* T138_;
						T134_ = (NIM_BOOL)0;
						T134_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_40));
						if (!T134_) goto LA135_;
						T137_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T137_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T138_ = (NimStringDesc*)0;
						T138_ = nsuStrip(T137_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						(*self).displayMaximum = nsuParseFloat(T138_);
					}
					goto LA6_;
					LA135_: ;
					{
						NIM_BOOL T140_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T143_;
						T140_ = (NIM_BOOL)0;
						T140_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_41));
						if (!T140_) goto LA141_;
						T143_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T143_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						unsureAsgnRef((void**) (&(*self).palette), nsuStrip(T143_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16));
					}
					goto LA6_;
					LA141_: ;
					{
						NIM_BOOL T145_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T148_;
						NimStringDesc* T149_;
						T145_ = (NIM_BOOL)0;
						T145_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_42));
						if (!T145_) goto LA146_;
						T148_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T148_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T149_ = (NimStringDesc*)0;
						T149_ = nsuStrip(T148_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						(*self).nodata = nsuParseFloat(T149_);
					}
					goto LA6_;
					LA146_: ;
					{
						NIM_BOOL T151_;
						NimStringDesc* v_3;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T154_;
						NimStringDesc* T155_;
						T151_ = (NIM_BOOL)0;
						T151_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_35));
						if (!T151_) goto LA152_;
						T154_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T154_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T155_ = (NimStringDesc*)0;
						T155_ = nsuStrip(T154_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						v_3 = nsuToLowerAsciiStr(T155_);
						{
							NIM_BOOL T158_;
							T158_ = (NIM_BOOL)0;
							T158_ = contains_bKoQGynT9bWCEn79aXG8be9aw(v_3, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_43));
							if (!T158_) goto LA159_;
							(*self).byteOrder = ((tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw) 0);
						}
						goto LA156_;
						LA159_: ;
						{
							(*self).byteOrder = ((tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw) 1);
						}
						LA156_: ;
					}
					goto LA6_;
					LA152_: ;
					{
						NIM_BOOL T163_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T166_;
						NimStringDesc* T167_;
						T163_ = (NIM_BOOL)0;
						T163_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_44));
						if (!T163_) goto LA164_;
						T166_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T166_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T167_ = (NimStringDesc*)0;
						T167_ = nsuStrip(T166_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						(*self).paletteNonlinearity = nsuParseFloat(T167_);
					}
					goto LA6_;
					LA164_: ;
					{
						NIM_BOOL T169_;
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T172_;
						NimStringDesc* T173_;
						NI T174_;
						NimStringDesc* T175_;
						T169_ = (NIM_BOOL)0;
						T169_ = contains_bKoQGynT9bWCEn79aXG8be9aw(lcLine, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_45));
						if (!T169_) goto LA170_;
						T172_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
						T172_ = nsuSplitString(line, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NI) -1));
						T173_ = (NimStringDesc*)0;
						T173_ = nsuStrip(T172_->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM_Y3cCMs4xzyrNE4rsvwdnGQ_16);
						(*self).metadata = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*self).metadata)->Sup, sizeof(NimStringDesc*));
						T174_ = (*self).metadata->Sup.len++;
						T175_ = (NimStringDesc*)0;
						T175_ = (*self).metadata->data[T174_]; (*self).metadata->data[T174_] = copyStringRC1(T173_);
						if (T175_) nimGCunrefNoCycle(T175_);
					}
					goto LA6_;
					LA170_: ;
					LA6_: ;
				} LA4: ;
			}
		}
		(*self).resolutionX = ((NF)(((NF)((*self).east) - (NF)((*self).west))) / (NF)(((NF) ((*self).columns))));
		(*self).resolutionY = ((NF)(((NF)((*self).north) - (NF)((*self).south))) / (NF)(((NF) ((*self).rows))));
		unsureAsgnRef((void**) (&(*self).values), newSeq_QEg0mebvlEuej5bmGcaclQ(((NI) ((NI)((*self).rows * (*self).columns)))));
		fileSize = nosgetFileSize((*self).dataFilename);
		buf = newSeq_OVoBJFASw7yjKnQkxoXCzw(((NI) (fileSize)));
		df = open_hqzpWQbdA2B8l9a6wwNoP4g((*self).dataFilename, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
		pushSafePoint(&TM_Y3cCMs4xzyrNE4rsvwdnGQ_46);
		TM_Y3cCMs4xzyrNE4rsvwdnGQ_46.status = _setjmp(TM_Y3cCMs4xzyrNE4rsvwdnGQ_46.context);
		if (TM_Y3cCMs4xzyrNE4rsvwdnGQ_46.status == 0) {
			NI T177_;
			tyObject_ByteOrderReader_QjX6XRQMB4wRVk9aWDcEeQQ bor;
			NI numPoints;
			T177_ = (NI)0;
			T177_ = readBytes_u45tKTCEtv32o47mnn9cWMg(df, buf->data, buf->Sup.len, ((NI) 0), ((NI) (fileSize)));
			T177_;
			memset((void*)(&bor), 0, sizeof(bor));
			chckNil((void*)(&bor));
			memset((void*)(&bor), 0, sizeof(bor));
			newByteOrderReader_wBmQ8d88r4Ig3UfUSerbWg(buf, (*self).byteOrder, ((NI) 0), (&bor));
			numPoints = (NI)((*self).rows * (*self).columns);
			switch ((*self).dataType) {
			case ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 0):
			{
				{
					NI i;
					NI volatile i_2;
					i = (NI)0;
					i_2 = ((NI) 0);
					{
						while (1) {
							if (!(i_2 < numPoints)) goto LA181;
							i = i_2;
							(*self).values->data[i] = readFloat64_Nj9aeK6evnfhHL5m3vUzwYwraster((&bor));
							i_2 += ((NI) 1);
						} LA181: ;
					}
				}
			}
			break;
			case ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 1):
			{
				{
					NI i_3;
					NI volatile i_4;
					i_3 = (NI)0;
					i_4 = ((NI) 0);
					{
						while (1) {
							NF32 T186_;
							if (!(i_4 < numPoints)) goto LA185;
							i_3 = i_4;
							T186_ = (NF32)0;
							T186_ = readFloat32_iegdcqKF0iRbudzM03sr0Qraster((&bor));
							(*self).values->data[i_3] = ((NF) (T186_));
							i_4 += ((NI) 1);
						} LA185: ;
					}
				}
			}
			break;
			case ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 2):
			{
				{
					NI i_5;
					NI volatile i_6;
					i_5 = (NI)0;
					i_6 = ((NI) 0);
					{
						while (1) {
							NI32 T191_;
							if (!(i_6 < numPoints)) goto LA190;
							i_5 = i_6;
							T191_ = (NI32)0;
							T191_ = readInt32_YpaWGTN1retCbzXwCs2lYAraster((&bor));
							(*self).values->data[i_5] = ((NF) (T191_));
							i_6 += ((NI) 1);
						} LA190: ;
					}
				}
			}
			break;
			case ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 3):
			{
				{
					NI i_7;
					NI volatile i_8;
					i_7 = (NI)0;
					i_8 = ((NI) 0);
					{
						while (1) {
							NI16 T196_;
							if (!(i_8 < numPoints)) goto LA195;
							i_7 = i_8;
							T196_ = (NI16)0;
							T196_ = readInt16_HUN2sABaNPqAgLYsUVbbZAraster((&bor));
							(*self).values->data[i_7] = ((NF) (T196_));
							i_8 += ((NI) 1);
						} LA195: ;
					}
				}
			}
			break;
			default:
			{
				{
					NI i_9;
					NI volatile i_10;
					i_9 = (NI)0;
					i_10 = ((NI) 0);
					{
						while (1) {
							NI8 T201_;
							if (!(i_10 < numPoints)) goto LA200;
							i_9 = i_10;
							T201_ = (NI8)0;
							T201_ = readInt8_g49bc3QmRiVKJqiOgAd6Hbgraster((&bor));
							(*self).values->data[i_9] = ((NF) (T201_));
							i_10 += ((NI) 1);
						} LA200: ;
					}
				}
			}
			break;
			}
			popSafePoint();
		}
		else {
			popSafePoint();
		}
		{
			close_BWnr8V7RERYno9bIdPmw8Hw_2(df);
		}
		if (TM_Y3cCMs4xzyrNE4rsvwdnGQ_46.status != 0) reraiseException();
		popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		close_BWnr8V7RERYno9bIdPmw8Hw_2(f);
	}
	if (TM_Y3cCMs4xzyrNE4rsvwdnGQ_12.status != 0) reraiseException();
}

N_NIMCALL(void, newRasterFromFile_gZRUEKxlbgHqMyK0NThKhg)(NimStringDesc* fileName, tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ* Result) {
	{
		NimStringDesc* T3_;
		NIM_BOOL T4_;
		T3_ = (NimStringDesc*)0;
		T3_ = nsuToLowerAsciiStr(fileName);
		T4_ = (NIM_BOOL)0;
		T4_ = nsuEndsWith(T3_, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_9));
		if (!T4_) goto LA5_;
		unsureAsgnRef((void**) (&(*Result).headerFilename), copyString(fileName));
		unsureAsgnRef((void**) (&(*Result).dataFilename), nsuReplaceStr(fileName, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_9), ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_10)));
	}
	goto LA1_;
	LA5_: ;
	{
		NimStringDesc* T8_;
		NIM_BOOL T9_;
		T8_ = (NimStringDesc*)0;
		T8_ = nsuToLowerAsciiStr(fileName);
		T9_ = (NIM_BOOL)0;
		T9_ = nsuEndsWith(T8_, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_10));
		if (!T9_) goto LA10_;
		unsureAsgnRef((void**) (&(*Result).headerFilename), nsuReplaceStr(fileName, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_10), ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_9)));
		unsureAsgnRef((void**) (&(*Result).dataFilename), copyString(fileName));
	}
	goto LA1_;
	LA10_: ;
	{
		tyObject_FileIOError_e5YQgQH5C8Fl9cRhRXJezhA* e;
		NimStringDesc* T13_;
		e = (tyObject_FileIOError_e5YQgQH5C8Fl9cRhRXJezhA*)0;
		e = (tyObject_FileIOError_e5YQgQH5C8Fl9cRhRXJezhA*) newObj((&NTI_RLjzwRut8ihej9aDTKbr77Q_), sizeof(tyObject_FileIOError_e5YQgQH5C8Fl9cRhRXJezhA));
		(*e).Sup.Sup.m_type = (&NTI_e5YQgQH5C8Fl9cRhRXJezhA_);
		T13_ = (NimStringDesc*)0;
		T13_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_11));
		if (T13_) nimGCunrefNoCycle(T13_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "FileIOError");
	}
	LA1_: ;
	read_ebB70bAWQPd5TX9cPi5HkrQ(Result);
}

N_NIMCALL(void, createFromOther_VKyOrWbwXA8ZinmUznutZA)(NimStringDesc* filename, tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ* other, tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ dataType, NF nodata, NIM_BOOL copyData, tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ* Result) {
	{
		NimStringDesc* T3_;
		NIM_BOOL T4_;
		T3_ = (NimStringDesc*)0;
		T3_ = nsuToLowerAsciiStr(filename);
		T4_ = (NIM_BOOL)0;
		T4_ = nsuEndsWith(T3_, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_9));
		if (!T4_) goto LA5_;
		unsureAsgnRef((void**) (&(*Result).headerFilename), copyString(filename));
		unsureAsgnRef((void**) (&(*Result).dataFilename), nsuReplaceStr(filename, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_9), ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_10)));
	}
	goto LA1_;
	LA5_: ;
	{
		NimStringDesc* T8_;
		NIM_BOOL T9_;
		T8_ = (NimStringDesc*)0;
		T8_ = nsuToLowerAsciiStr(filename);
		T9_ = (NIM_BOOL)0;
		T9_ = nsuEndsWith(T8_, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_10));
		if (!T9_) goto LA10_;
		unsureAsgnRef((void**) (&(*Result).headerFilename), nsuReplaceStr(filename, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_10), ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_9)));
		unsureAsgnRef((void**) (&(*Result).dataFilename), copyString(filename));
	}
	goto LA1_;
	LA10_: ;
	{
		tyObject_FileIOError_e5YQgQH5C8Fl9cRhRXJezhA* e;
		NimStringDesc* T13_;
		e = (tyObject_FileIOError_e5YQgQH5C8Fl9cRhRXJezhA*)0;
		e = (tyObject_FileIOError_e5YQgQH5C8Fl9cRhRXJezhA*) newObj((&NTI_RLjzwRut8ihej9aDTKbr77Q_), sizeof(tyObject_FileIOError_e5YQgQH5C8Fl9cRhRXJezhA));
		(*e).Sup.Sup.m_type = (&NTI_e5YQgQH5C8Fl9cRhRXJezhA_);
		T13_ = (NimStringDesc*)0;
		T13_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_11));
		if (T13_) nimGCunrefNoCycle(T13_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "FileIOError");
	}
	LA1_: ;
	(*Result).north = (*other).north;
	(*Result).south = (*other).south;
	(*Result).east = (*other).east;
	(*Result).west = (*other).west;
	(*Result).rows = (*other).rows;
	(*Result).columns = (*other).columns;
	(*Result).resolutionX = (*other).resolutionX;
	(*Result).resolutionY = (*other).resolutionY;
	(*Result).stacks = (*other).stacks;
	{
		tyEnum_FloatClass_pPga1yW9b8J9cwNnm9b1aPRnA T16_;
		T16_ = (tyEnum_FloatClass_pPga1yW9b8J9cwNnm9b1aPRnA)0;
		T16_ = classify_rfodLs2J9b87EDgWnWZoObA(nodata);
		if (!(T16_ == ((tyEnum_FloatClass_pPga1yW9b8J9cwNnm9b1aPRnA) 6))) goto LA17_;
		(*Result).nodata = (*other).nodata;
	}
	goto LA14_;
	LA17_: ;
	{
		(*Result).nodata = nodata;
	}
	LA14_: ;
	(*Result).dataScale = (*other).dataScale;
	{
		if (!(dataType == ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 5))) goto LA22_;
		(*Result).dataType = (*other).dataType;
	}
	goto LA20_;
	LA22_: ;
	{
		(*Result).dataType = dataType;
	}
	LA20_: ;
	unsureAsgnRef((void**) (&(*Result).palette), copyString((*other).palette));
	(*Result).paletteNonlinearity = (*other).paletteNonlinearity;
	unsureAsgnRef((void**) (&(*Result).projection), copyString((*other).projection));
	unsureAsgnRef((void**) (&(*Result).zUnits), copyString((*other).zUnits));
	unsureAsgnRef((void**) (&(*Result).xyUnits), copyString((*other).xyUnits));
	(*Result).byteOrder = (*other).byteOrder;
	(*Result).minimum = INF;
	(*Result).maximum = -INF;
	(*Result).displayMinimum = INF;
	(*Result).displayMaximum = -INF;
	{
		if (!!(copyData)) goto LA27_;
		unsureAsgnRef((void**) (&(*Result).values), repeat_pBHAjECB1SlEt8MwweaBAA((*Result).nodata, ((NI) ((NI)((*Result).rows * (*Result).columns)))));
	}
	goto LA25_;
	LA27_: ;
	{
		genericSeqAssign((&(*Result).values), (*other).values, (&NTI_Zj5xKXgsXnI4n4hPS6nACA_));
	}
	LA25_: ;
	unsureAsgnRef((void**) (&(*Result).metadata), newSeq_9cL6dIz2UWtIh3FeS5x4hxA(((NI) 0)));
}

N_NIMCALL(void, calculateMinAndMax_UWLXtJXzLzoXimKlJPPcrw)(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ* self) {
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)((*self).rows * (*self).columns);
		i_2 = ((NI) 0);
		{
			while (1) {
				NF z;
				if (!(i_2 < colontmp_)) goto LA3;
				i = i_2;
				z = (*self).values->data[i];
				{
					if (!!((z == (*self).nodata))) goto LA6_;
					{
						if (!(z < (*self).minimum)) goto LA10_;
						(*self).minimum = z;
					}
					LA10_: ;
					{
						if (!((*self).maximum < z)) goto LA14_;
						(*self).maximum = z;
					}
					LA14_: ;
				}
				LA6_: ;
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
}

static N_INLINE(void, writeLine_rBQVO3cm3BhnA9aEFD7PG6Qraster)(FILE* f, NimStringDesc** x, NI xLen_0) {
	{
		NimStringDesc* i;
		NI i_2;
		i = (NimStringDesc*)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < xLen_0)) goto LA3;
				i = x[i_2];
				write_c4mGyJBvK73pdM22jiweKQ(f, i);
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_50));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, dollar__ecmw559aInnl3DSY6bSGsDA)(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ* self) {
	NimStringDesc* result;
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T2_;
	NimStringDesc* T3_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T4_;
	NimStringDesc* T5_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T6_;
	NimStringDesc* T7_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T8_;
	NimStringDesc* T9_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T10_;
	NimStringDesc* T11_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T12_;
	NimStringDesc* T13_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T14_;
	NimStringDesc* T15_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T16_;
	NimStringDesc* T17_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T23_;
	NimStringDesc* T24_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T25_;
	NimStringDesc* T26_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T27_;
	NimStringDesc* T28_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T29_;
	NimStringDesc* T30_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T31_;
	NimStringDesc* T32_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T33_;
	NimStringDesc* T34_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T35_;
	NimStringDesc* T36_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T37_;
	NimStringDesc* T38_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T44_;
	NimStringDesc* T45_;
	result = (NimStringDesc*)0;
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = nimFloatToStr((*self).minimum);
	result = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_51), T1_, 1);
	memset((void*)T2_, 0, sizeof(T2_));
	T2_[0] = nimFloatToStr((*self).maximum);
	T3_ = (NimStringDesc*)0;
	T3_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_52), T2_, 1);
	result = resizeString(result, T3_->Sup.len + 0);
appendString(result, T3_);
	memset((void*)T4_, 0, sizeof(T4_));
	T4_[0] = nimIntToStr((*self).rows);
	T5_ = (NimStringDesc*)0;
	T5_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_53), T4_, 1);
	result = resizeString(result, T5_->Sup.len + 0);
appendString(result, T5_);
	memset((void*)T6_, 0, sizeof(T6_));
	T6_[0] = nimIntToStr((*self).columns);
	T7_ = (NimStringDesc*)0;
	T7_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_54), T6_, 1);
	result = resizeString(result, T7_->Sup.len + 0);
appendString(result, T7_);
	memset((void*)T8_, 0, sizeof(T8_));
	T8_[0] = nimIntToStr((*self).stacks);
	T9_ = (NimStringDesc*)0;
	T9_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_55), T8_, 1);
	result = resizeString(result, T9_->Sup.len + 0);
appendString(result, T9_);
	memset((void*)T10_, 0, sizeof(T10_));
	T10_[0] = nimFloatToStr((*self).north);
	T11_ = (NimStringDesc*)0;
	T11_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_56), T10_, 1);
	result = resizeString(result, T11_->Sup.len + 0);
appendString(result, T11_);
	memset((void*)T12_, 0, sizeof(T12_));
	T12_[0] = nimFloatToStr((*self).south);
	T13_ = (NimStringDesc*)0;
	T13_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_57), T12_, 1);
	result = resizeString(result, T13_->Sup.len + 0);
appendString(result, T13_);
	memset((void*)T14_, 0, sizeof(T14_));
	T14_[0] = nimFloatToStr((*self).east);
	T15_ = (NimStringDesc*)0;
	T15_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_58), T14_, 1);
	result = resizeString(result, T15_->Sup.len + 0);
appendString(result, T15_);
	memset((void*)T16_, 0, sizeof(T16_));
	T16_[0] = nimFloatToStr((*self).west);
	T17_ = (NimStringDesc*)0;
	T17_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_59), T16_, 1);
	result = resizeString(result, T17_->Sup.len + 0);
appendString(result, T17_);
	switch ((*self).dataType) {
	case ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 0):
	{
		result = resizeString(result, 18);
appendString(result, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_60));
	}
	break;
	case ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 1):
	{
		result = resizeString(result, 17);
appendString(result, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_61));
	}
	break;
	case ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 2):
	{
		result = resizeString(result, 15);
appendString(result, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_62));
	}
	break;
	case ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 3):
	{
		result = resizeString(result, 19);
appendString(result, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_63));
	}
	break;
	default:
	{
		result = resizeString(result, 16);
appendString(result, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_64));
	}
	break;
	}
	memset((void*)T23_, 0, sizeof(T23_));
	T23_[0] = copyString((*self).zUnits);
	T24_ = (NimStringDesc*)0;
	T24_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_65), T23_, 1);
	result = resizeString(result, T24_->Sup.len + 0);
appendString(result, T24_);
	memset((void*)T25_, 0, sizeof(T25_));
	T25_[0] = copyString((*self).xyUnits);
	T26_ = (NimStringDesc*)0;
	T26_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_66), T25_, 1);
	result = resizeString(result, T26_->Sup.len + 0);
appendString(result, T26_);
	memset((void*)T27_, 0, sizeof(T27_));
	T27_[0] = copyString((*self).projection);
	T28_ = (NimStringDesc*)0;
	T28_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_67), T27_, 1);
	result = resizeString(result, T28_->Sup.len + 0);
appendString(result, T28_);
	memset((void*)T29_, 0, sizeof(T29_));
	T29_[0] = copyString(reprEnum((NI)(*self).dataScale, (&NTI_RrPL9cDKg0HP9c6NuFDso29bA_)));
	T30_ = (NimStringDesc*)0;
	T30_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_68), T29_, 1);
	result = resizeString(result, T30_->Sup.len + 0);
appendString(result, T30_);
	memset((void*)T31_, 0, sizeof(T31_));
	T31_[0] = nimFloatToStr((*self).displayMinimum);
	T32_ = (NimStringDesc*)0;
	T32_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_69), T31_, 1);
	result = resizeString(result, T32_->Sup.len + 0);
appendString(result, T32_);
	memset((void*)T33_, 0, sizeof(T33_));
	T33_[0] = nimFloatToStr((*self).displayMaximum);
	T34_ = (NimStringDesc*)0;
	T34_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_70), T33_, 1);
	result = resizeString(result, T34_->Sup.len + 0);
appendString(result, T34_);
	memset((void*)T35_, 0, sizeof(T35_));
	T35_[0] = copyString((*self).palette);
	T36_ = (NimStringDesc*)0;
	T36_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_71), T35_, 1);
	result = resizeString(result, T36_->Sup.len + 0);
appendString(result, T36_);
	memset((void*)T37_, 0, sizeof(T37_));
	T37_[0] = nimFloatToStr((*self).nodata);
	T38_ = (NimStringDesc*)0;
	T38_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_72), T37_, 1);
	result = resizeString(result, T38_->Sup.len + 0);
appendString(result, T38_);
	{
		if (!((*self).byteOrder == ((tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw) 0))) goto LA41_;
		result = resizeString(result, 26);
appendString(result, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_73));
	}
	goto LA39_;
	LA41_: ;
	{
		result = resizeString(result, 23);
appendString(result, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_74));
	}
	LA39_: ;
	memset((void*)T44_, 0, sizeof(T44_));
	T44_[0] = copyString((*self).palette);
	T45_ = (NimStringDesc*)0;
	T45_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_75), T44_, 1);
	result = resizeString(result, T45_->Sup.len + 0);
appendString(result, T45_);
	{
		NimStringDesc* v;
		tySequence_sM4lkSb7zS6F7OVMvW9cffQ* colontmp_;
		NI i;
		NI L;
		NI T47_;
		v = (NimStringDesc*)0;
		colontmp_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
		colontmp_ = (*self).metadata;
		i = ((NI) 0);
		T47_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T47_;
		{
			while (1) {
				tyArray_nHXaesL0DJZHyVS07ARPRA T50_;
				NimStringDesc* T51_;
				if (!(i < L)) goto LA49;
				v = colontmp_->data[i];
				memset((void*)T50_, 0, sizeof(T50_));
				T50_[0] = nsuReplaceStr(v, ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_15), ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_77));
				T51_ = (NimStringDesc*)0;
				T51_ = nsuFormatVarargs(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_76), T50_, 1);
				result = resizeString(result, T51_->Sup.len + 0);
appendString(result, T51_);
				i += ((NI) 1);
			} LA49: ;
		}
	}
	return result;
}

static N_INLINE(void, writeFloat64_NTvU1iusBzUqugysmVpL0wraster)(tyObject_ByteOrderWriter_mZRGtGKlNjXmPT9b8N9avxsA* b, NF* value) {
	{
		NIM_BOOL T3_;
		NI T4_;
		tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T4_ = ((*b).data ? (*b).data->Sup.len : 0);
		T3_ = (T4_ < (NI)((*b).pos + ((NI) 8)));
		if (T3_) goto LA5_;
		T3_ = ((*b).pos < ((NI) 0));
		LA5_: ;
		if (!T3_) goto LA6_;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
		(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
		T8_ = (NimStringDesc*)0;
		T8_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_79));
		if (T8_) nimGCunrefNoCycle(T8_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "IndexError");
	}
	LA6_: ;
	{
		if (!((*b).endian == ((tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw) 0))) goto LA11_;
		littleEndian64_IzdisrH4sYnsItUtxSkomAraster(((void*) ((&(*b).data->data[(*b).pos]))), ((void*) (value)));
	}
	goto LA9_;
	LA11_: ;
	{
		bigEndian64_IzdisrH4sYnsItUtxSkomA_2raster(((void*) ((&(*b).data->data[(*b).pos]))), ((void*) (value)));
	}
	LA9_: ;
	(*b).pos += ((NI) 8);
}

static N_INLINE(void, writeFloat32_04Wuv1SIlKOZr9cZdef0hZwraster)(tyObject_ByteOrderWriter_mZRGtGKlNjXmPT9b8N9avxsA* b, NF32* value) {
	{
		NIM_BOOL T3_;
		NI T4_;
		tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T4_ = ((*b).data ? (*b).data->Sup.len : 0);
		T3_ = (T4_ < (NI)((*b).pos + ((NI) 4)));
		if (T3_) goto LA5_;
		T3_ = ((*b).pos < ((NI) 0));
		LA5_: ;
		if (!T3_) goto LA6_;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
		(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
		T8_ = (NimStringDesc*)0;
		T8_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_79));
		if (T8_) nimGCunrefNoCycle(T8_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "IndexError");
	}
	LA6_: ;
	{
		if (!((*b).endian == ((tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw) 0))) goto LA11_;
		littleEndian32_IzdisrH4sYnsItUtxSkomA_4raster(((void*) ((&(*b).data->data[(*b).pos]))), ((void*) (value)));
	}
	goto LA9_;
	LA11_: ;
	{
		bigEndian32_IzdisrH4sYnsItUtxSkomA_5raster(((void*) ((&(*b).data->data[(*b).pos]))), ((void*) (value)));
	}
	LA9_: ;
	(*b).pos += ((NI) 4);
}

static N_INLINE(void, writeInt32_QA2F6NQYDR8mdNGxjEyzcgraster)(tyObject_ByteOrderWriter_mZRGtGKlNjXmPT9b8N9avxsA* b, NI32* value) {
	{
		NIM_BOOL T3_;
		NI T4_;
		tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T4_ = ((*b).data ? (*b).data->Sup.len : 0);
		T3_ = (T4_ < (NI)((*b).pos + ((NI) 4)));
		if (T3_) goto LA5_;
		T3_ = ((*b).pos < ((NI) 0));
		LA5_: ;
		if (!T3_) goto LA6_;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
		(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
		T8_ = (NimStringDesc*)0;
		T8_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_79));
		if (T8_) nimGCunrefNoCycle(T8_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "IndexError");
	}
	LA6_: ;
	{
		if (!((*b).endian == ((tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw) 0))) goto LA11_;
		littleEndian32_IzdisrH4sYnsItUtxSkomA_4raster(((void*) ((&(*b).data->data[(*b).pos]))), ((void*) (value)));
	}
	goto LA9_;
	LA11_: ;
	{
		bigEndian32_IzdisrH4sYnsItUtxSkomA_5raster(((void*) ((&(*b).data->data[(*b).pos]))), ((void*) (value)));
	}
	LA9_: ;
	(*b).pos += ((NI) 4);
}

static N_INLINE(void, writeInt16_7qbGaWN9amZW9bykPdKTFaUQraster)(tyObject_ByteOrderWriter_mZRGtGKlNjXmPT9b8N9avxsA* b, NI16* value) {
	{
		NIM_BOOL T3_;
		NI T4_;
		tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T4_ = ((*b).data ? (*b).data->Sup.len : 0);
		T3_ = (T4_ < (NI)((*b).pos + ((NI) 2)));
		if (T3_) goto LA5_;
		T3_ = ((*b).pos < ((NI) 0));
		LA5_: ;
		if (!T3_) goto LA6_;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
		(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
		T8_ = (NimStringDesc*)0;
		T8_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_79));
		if (T8_) nimGCunrefNoCycle(T8_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "IndexError");
	}
	LA6_: ;
	{
		if (!((*b).endian == ((tyEnum_Endianness_0BVYNY0K9cz7BUPI3AnbEQw) 0))) goto LA11_;
		littleEndian16_IzdisrH4sYnsItUtxSkomA_7raster(((void*) ((&(*b).data->data[(*b).pos]))), ((void*) (value)));
	}
	goto LA9_;
	LA11_: ;
	{
		bigEndian16_IzdisrH4sYnsItUtxSkomA_8raster(((void*) ((&(*b).data->data[(*b).pos]))), ((void*) (value)));
	}
	LA9_: ;
	(*b).pos += ((NI) 2);
}

static N_INLINE(void, writeInt8_zaZ7wXN15zKjT9akG9c3G76Qraster)(tyObject_ByteOrderWriter_mZRGtGKlNjXmPT9b8N9avxsA* b, NI8* value) {
	{
		NIM_BOOL T3_;
		NI T4_;
		tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T4_ = ((*b).data ? (*b).data->Sup.len : 0);
		T3_ = (T4_ < (NI)((*b).pos + ((NI) 1)));
		if (T3_) goto LA5_;
		T3_ = ((*b).pos < ((NI) 0));
		LA5_: ;
		if (!T3_) goto LA6_;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
		(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
		T8_ = (NimStringDesc*)0;
		T8_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_79));
		if (T8_) nimGCunrefNoCycle(T8_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "IndexError");
	}
	LA6_: ;
	(*b).data->data[(*b).pos] = ((NU8) ((*value)));
	(*b).pos += ((NI) 1);
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	result = (Exception*)0;
	result = currException_9bVPeDJlYTi9bQApZpfH8wjg;
	return result;
}

static N_INLINE(NimStringDesc*, getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qraster)(void) {
	NimStringDesc* result;
	Exception* e;
{	result = (NimStringDesc*)0;
	e = getCurrentException();
	{
		if (!(e == NIM_NIL)) goto LA3_;
		result = copyString(((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_82));
	}
	goto LA1_;
	LA3_: ;
	{
		result = copyString((*e).message);
	}
	LA1_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException_9bVPeDJlYTi9bQApZpfH8wjg), (*currException_9bVPeDJlYTi9bQApZpfH8wjg).up);
}

N_NIMCALL(void, write_ebB70bAWQPd5TX9cPi5HkrQ_2)(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ* self) {
	TSafePoint TM_Y3cCMs4xzyrNE4rsvwdnGQ_48;
	pushSafePoint(&TM_Y3cCMs4xzyrNE4rsvwdnGQ_48);
	TM_Y3cCMs4xzyrNE4rsvwdnGQ_48.status = _setjmp(TM_Y3cCMs4xzyrNE4rsvwdnGQ_48.context);
	if (TM_Y3cCMs4xzyrNE4rsvwdnGQ_48.status == 0) {
		FILE* o;
		TSafePoint TM_Y3cCMs4xzyrNE4rsvwdnGQ_49;
		calculateMinAndMax_UWLXtJXzLzoXimKlJPPcrw(self);
		{
			tyEnum_FloatClass_pPga1yW9b8J9cwNnm9b1aPRnA T4_;
			T4_ = (tyEnum_FloatClass_pPga1yW9b8J9cwNnm9b1aPRnA)0;
			T4_ = classify_rfodLs2J9b87EDgWnWZoObA((*self).displayMaximum);
			if (!(T4_ == ((tyEnum_FloatClass_pPga1yW9b8J9cwNnm9b1aPRnA) 6))) goto LA5_;
			(*self).displayMaximum = (*self).maximum;
		}
		LA5_: ;
		{
			tyEnum_FloatClass_pPga1yW9b8J9cwNnm9b1aPRnA T9_;
			T9_ = (tyEnum_FloatClass_pPga1yW9b8J9cwNnm9b1aPRnA)0;
			T9_ = classify_rfodLs2J9b87EDgWnWZoObA((*self).displayMinimum);
			if (!(T9_ == ((tyEnum_FloatClass_pPga1yW9b8J9cwNnm9b1aPRnA) 5))) goto LA10_;
			(*self).displayMinimum = (*self).minimum;
		}
		LA10_: ;
		o = open_hqzpWQbdA2B8l9a6wwNoP4g((*self).headerFilename, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 1), ((NI) -1));
		pushSafePoint(&TM_Y3cCMs4xzyrNE4rsvwdnGQ_49);
		TM_Y3cCMs4xzyrNE4rsvwdnGQ_49.status = _setjmp(TM_Y3cCMs4xzyrNE4rsvwdnGQ_49.context);
		if (TM_Y3cCMs4xzyrNE4rsvwdnGQ_49.status == 0) {
			tyArray_nHXaesL0DJZHyVS07ARPRA T13_;
			NI dataSize;
			NI fileSize;
			FILE* df;
			TSafePoint TM_Y3cCMs4xzyrNE4rsvwdnGQ_78;
			memset((void*)T13_, 0, sizeof(T13_));
			T13_[0] = dollar__ecmw559aInnl3DSY6bSGsDA((&(*self)));
			writeLine_rBQVO3cm3BhnA9aEFD7PG6Qraster(o, T13_, 1);
			{
				if (!((*self).dataType == ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 0))) goto LA16_;
				dataSize = ((NI) 8);
			}
			goto LA14_;
			LA16_: ;
			{
				NIM_BOOL T19_;
				T19_ = (NIM_BOOL)0;
				T19_ = ((*self).dataType == ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 1));
				if (T19_) goto LA20_;
				T19_ = ((*self).dataType == ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 2));
				LA20_: ;
				if (!T19_) goto LA21_;
				dataSize = ((NI) 4);
			}
			goto LA14_;
			LA21_: ;
			{
				if (!((*self).dataType == ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 3))) goto LA24_;
				dataSize = ((NI) 2);
			}
			goto LA14_;
			LA24_: ;
			{
				dataSize = ((NI) 1);
			}
			LA14_: ;
			fileSize = (NI)((NI)(dataSize * (*self).rows) * (*self).columns);
			df = open_hqzpWQbdA2B8l9a6wwNoP4g((*self).dataFilename, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 1), ((NI) -1));
			pushSafePoint(&TM_Y3cCMs4xzyrNE4rsvwdnGQ_78);
			TM_Y3cCMs4xzyrNE4rsvwdnGQ_78.status = _setjmp(TM_Y3cCMs4xzyrNE4rsvwdnGQ_78.context);
			if (TM_Y3cCMs4xzyrNE4rsvwdnGQ_78.status == 0) {
				tyObject_ByteOrderWriter_mZRGtGKlNjXmPT9b8N9avxsA bow;
				NI numPoints;
				NI T48_;
				memset((void*)(&bow), 0, sizeof(bow));
				chckNil((void*)(&bow));
				memset((void*)(&bow), 0, sizeof(bow));
				newByteOrderWriter_i9bKyO6VqGAi1lK9cGnNKLZg(fileSize, (*self).byteOrder, ((NI) 0), (&bow));
				numPoints = (NI)((*self).rows * (*self).columns);
				switch ((*self).dataType) {
				case ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 0):
				{
					{
						NI i;
						NI volatile i_2;
						i = (NI)0;
						i_2 = ((NI) 0);
						{
							while (1) {
								if (!(i_2 < numPoints)) goto LA31;
								i = i_2;
								writeFloat64_NTvU1iusBzUqugysmVpL0wraster((&bow), (&(*self).values->data[i]));
								i_2 += ((NI) 1);
							} LA31: ;
						}
					}
				}
				break;
				case ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 1):
				{
					NF32 volatile val;
					val = (NF32)0;
					{
						NI i_3;
						NI volatile i_4;
						i_3 = (NI)0;
						i_4 = ((NI) 0);
						{
							while (1) {
								if (!(i_4 < numPoints)) goto LA35;
								i_3 = i_4;
								val = ((NF32) ((*self).values->data[i_3]));
								writeFloat32_04Wuv1SIlKOZr9cZdef0hZwraster((&bow), (&val));
								i_4 += ((NI) 1);
							} LA35: ;
						}
					}
				}
				break;
				case ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 2):
				{
					NI32 volatile val_2;
					val_2 = (NI32)0;
					{
						NI i_5;
						NI volatile i_6;
						i_5 = (NI)0;
						i_6 = ((NI) 0);
						{
							while (1) {
								if (!(i_6 < numPoints)) goto LA39;
								i_5 = i_6;
								val_2 = ((NI32) ((*self).values->data[i_5]));
								writeInt32_QA2F6NQYDR8mdNGxjEyzcgraster((&bow), (&val_2));
								i_6 += ((NI) 1);
							} LA39: ;
						}
					}
				}
				break;
				case ((tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ) 3):
				{
					NI16 volatile val_3;
					val_3 = (NI16)0;
					{
						NI i_7;
						NI volatile i_8;
						i_7 = (NI)0;
						i_8 = ((NI) 0);
						{
							while (1) {
								if (!(i_8 < numPoints)) goto LA43;
								i_7 = i_8;
								val_3 = ((NI16) ((*self).values->data[i_7]));
								writeInt16_7qbGaWN9amZW9bykPdKTFaUQraster((&bow), (&val_3));
								i_8 += ((NI) 1);
							} LA43: ;
						}
					}
				}
				break;
				default:
				{
					NI8 volatile val_4;
					val_4 = (NI8)0;
					{
						NI i_9;
						NI volatile i_10;
						i_9 = (NI)0;
						i_10 = ((NI) 0);
						{
							while (1) {
								if (!(i_10 < numPoints)) goto LA47;
								i_9 = i_10;
								val_4 = ((NI8) ((*self).values->data[i_9]));
								writeInt8_zaZ7wXN15zKjT9akG9c3G76Qraster((&bow), (&val_4));
								i_10 += ((NI) 1);
							} LA47: ;
						}
					}
				}
				break;
				}
				T48_ = (NI)0;
				T48_ = writeBytes_g0nTVLIZgU2QDdGZlYBRPw(df, bow.data->data, bow.data->Sup.len, ((NI) 0), ((NI) (fileSize)));
				T48_;
				popSafePoint();
			}
			else {
				popSafePoint();
			}
			{
				close_BWnr8V7RERYno9bIdPmw8Hw_2(df);
			}
			if (TM_Y3cCMs4xzyrNE4rsvwdnGQ_78.status != 0) reraiseException();
			popSafePoint();
		}
		else {
			popSafePoint();
		}
		{
			close_BWnr8V7RERYno9bIdPmw8Hw_2(o);
		}
		if (TM_Y3cCMs4xzyrNE4rsvwdnGQ_49.status != 0) reraiseException();
		popSafePoint();
	}
	else {
		popSafePoint();
		{
			Exception* T55_;
			NimStringDesc* T56_;
			TM_Y3cCMs4xzyrNE4rsvwdnGQ_48.status = 0;
			T55_ = (Exception*)0;
			T55_ = getCurrentException();
			T56_ = (NimStringDesc*)0;
			T56_ = getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qraster();
			printf("%s%s%s%s\012", ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_80)? (((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_80))->data:"nil", reprAny(T55_, (&NTI_oUKtBcKRdK6usj8RWrlp6A_))? (reprAny(T55_, (&NTI_oUKtBcKRdK6usj8RWrlp6A_)))->data:"nil", ((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_81)? (((NimStringDesc*) &TM_Y3cCMs4xzyrNE4rsvwdnGQ_81))->data:"nil", T56_? (T56_)->data:"nil");
			fflush(stdout);
			popCurrentException();
		}
	}
	if (TM_Y3cCMs4xzyrNE4rsvwdnGQ_48.status != 0) reraiseException();
}
NIM_EXTERNC N_NOINLINE(void, unknown_rasterInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_rasterDatInit000)(void) {
static TNimNode* TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[26];
static TNimNode* TM_Y3cCMs4xzyrNE4rsvwdnGQ_3[6];
NI TM_Y3cCMs4xzyrNE4rsvwdnGQ_5;
static char* NIM_CONST TM_Y3cCMs4xzyrNE4rsvwdnGQ_4[6] = {
"f64", 
"f32", 
"i32", 
"i16", 
"i8", 
"none"};
static TNimNode* TM_Y3cCMs4xzyrNE4rsvwdnGQ_6[3];
NI TM_Y3cCMs4xzyrNE4rsvwdnGQ_8;
static char* NIM_CONST TM_Y3cCMs4xzyrNE4rsvwdnGQ_7[3] = {
"continuous", 
"categorical", 
"boolean"};
static TNimNode TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[39];
NTI_QuEIJJ9arZP4gpDlFzlysJQ_.size = sizeof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ);
NTI_QuEIJJ9arZP4gpDlFzlysJQ_.kind = 18;
NTI_QuEIJJ9arZP4gpDlFzlysJQ_.base = 0;
NTI_QuEIJJ9arZP4gpDlFzlysJQ_.flags = 2;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[0] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[1];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[1].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[1].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, headerFilename);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[1].name = "headerFilename";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[1] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[2];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[2].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[2].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, dataFilename);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[2].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[2].name = "dataFilename";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[2] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[3];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[3].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[3].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, minimum);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[3].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[3].name = "minimum";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[3] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[4];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[4].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[4].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, maximum);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[4].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[4].name = "maximum";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[4] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[5];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[5].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[5].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, rows);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[5].name = "rows";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[5] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[6];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[6].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[6].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, columns);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[6].name = "columns";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[6] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[7];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[7].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[7].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, stacks);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[7].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[7].name = "stacks";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[7] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[8];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[8].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[8].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, north);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[8].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[8].name = "north";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[8] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[9];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[9].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[9].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, south);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[9].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[9].name = "south";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[9] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[10];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[10].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[10].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, east);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[10].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[10].name = "east";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[10] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[11];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[11].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[11].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, west);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[11].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[11].name = "west";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[11] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[12];
NTI_VeybIFcMcPMXNvVQ9cAA9a9bQ_.size = sizeof(tyEnum_DataType_VeybIFcMcPMXNvVQ9cAA9a9bQ);
NTI_VeybIFcMcPMXNvVQ9cAA9a9bQ_.kind = 14;
NTI_VeybIFcMcPMXNvVQ9cAA9a9bQ_.base = 0;
NTI_VeybIFcMcPMXNvVQ9cAA9a9bQ_.flags = 3;
for (TM_Y3cCMs4xzyrNE4rsvwdnGQ_5 = 0; TM_Y3cCMs4xzyrNE4rsvwdnGQ_5 < 6; TM_Y3cCMs4xzyrNE4rsvwdnGQ_5++) {
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[TM_Y3cCMs4xzyrNE4rsvwdnGQ_5+13].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[TM_Y3cCMs4xzyrNE4rsvwdnGQ_5+13].offset = TM_Y3cCMs4xzyrNE4rsvwdnGQ_5;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[TM_Y3cCMs4xzyrNE4rsvwdnGQ_5+13].name = TM_Y3cCMs4xzyrNE4rsvwdnGQ_4[TM_Y3cCMs4xzyrNE4rsvwdnGQ_5];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_3[TM_Y3cCMs4xzyrNE4rsvwdnGQ_5] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[TM_Y3cCMs4xzyrNE4rsvwdnGQ_5+13];
}
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[19].len = 6; TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[19].kind = 2; TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[19].sons = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_3[0];
NTI_VeybIFcMcPMXNvVQ9cAA9a9bQ_.node = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[19];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[12].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[12].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, dataType);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[12].typ = (&NTI_VeybIFcMcPMXNvVQ9cAA9a9bQ_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[12].name = "dataType";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[12] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[20];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[20].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[20].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, zUnits);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[20].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[20].name = "zUnits";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[13] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[21];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[21].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[21].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, xyUnits);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[21].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[21].name = "xyUnits";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[14] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[22];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[22].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[22].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, projection);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[22].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[22].name = "projection";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[15] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[23];
NTI_RrPL9cDKg0HP9c6NuFDso29bA_.size = sizeof(tyEnum_DataScale_RrPL9cDKg0HP9c6NuFDso29bA);
NTI_RrPL9cDKg0HP9c6NuFDso29bA_.kind = 14;
NTI_RrPL9cDKg0HP9c6NuFDso29bA_.base = 0;
NTI_RrPL9cDKg0HP9c6NuFDso29bA_.flags = 3;
for (TM_Y3cCMs4xzyrNE4rsvwdnGQ_8 = 0; TM_Y3cCMs4xzyrNE4rsvwdnGQ_8 < 3; TM_Y3cCMs4xzyrNE4rsvwdnGQ_8++) {
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[TM_Y3cCMs4xzyrNE4rsvwdnGQ_8+24].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[TM_Y3cCMs4xzyrNE4rsvwdnGQ_8+24].offset = TM_Y3cCMs4xzyrNE4rsvwdnGQ_8;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[TM_Y3cCMs4xzyrNE4rsvwdnGQ_8+24].name = TM_Y3cCMs4xzyrNE4rsvwdnGQ_7[TM_Y3cCMs4xzyrNE4rsvwdnGQ_8];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_6[TM_Y3cCMs4xzyrNE4rsvwdnGQ_8] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[TM_Y3cCMs4xzyrNE4rsvwdnGQ_8+24];
}
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[27].len = 3; TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[27].kind = 2; TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[27].sons = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_6[0];
NTI_RrPL9cDKg0HP9c6NuFDso29bA_.node = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[27];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[23].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[23].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, dataScale);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[23].typ = (&NTI_RrPL9cDKg0HP9c6NuFDso29bA_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[23].name = "dataScale";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[16] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[28];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[28].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[28].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, displayMinimum);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[28].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[28].name = "displayMinimum";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[17] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[29];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[29].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[29].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, displayMaximum);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[29].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[29].name = "displayMaximum";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[18] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[30];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[30].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[30].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, palette);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[30].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[30].name = "palette";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[19] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[31];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[31].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[31].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, nodata);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[31].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[31].name = "nodata";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[20] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[32];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[32].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[32].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, byteOrder);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[32].typ = (&NTI_0BVYNY0K9cz7BUPI3AnbEQw_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[32].name = "byteOrder";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[21] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[33];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[33].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[33].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, paletteNonlinearity);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[33].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[33].name = "paletteNonlinearity";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[22] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[34];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[34].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[34].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, resolutionX);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[34].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[34].name = "resolutionX";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[23] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[35];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[35].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[35].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, resolutionY);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[35].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[35].name = "resolutionY";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[24] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[36];
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[36].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[36].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, metadata);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[36].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[36].name = "metadata";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[25] = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[37];
NTI_Zj5xKXgsXnI4n4hPS6nACA_.size = sizeof(tySequence_Zj5xKXgsXnI4n4hPS6nACA*);
NTI_Zj5xKXgsXnI4n4hPS6nACA_.kind = 24;
NTI_Zj5xKXgsXnI4n4hPS6nACA_.base = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
NTI_Zj5xKXgsXnI4n4hPS6nACA_.flags = 2;
NTI_Zj5xKXgsXnI4n4hPS6nACA_.marker = Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[37].kind = 1;
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[37].offset = offsetof(tyObject_Raster_QuEIJJ9arZP4gpDlFzlysJQ, values);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[37].typ = (&NTI_Zj5xKXgsXnI4n4hPS6nACA_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[37].name = "values";
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[0].len = 26; TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[0].kind = 2; TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[0].sons = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_2[0];
NTI_QuEIJJ9arZP4gpDlFzlysJQ_.node = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[0];
NTI_e5YQgQH5C8Fl9cRhRXJezhA_.size = sizeof(tyObject_FileIOError_e5YQgQH5C8Fl9cRhRXJezhA);
NTI_e5YQgQH5C8Fl9cRhRXJezhA_.kind = 17;
NTI_e5YQgQH5C8Fl9cRhRXJezhA_.base = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[38].len = 0; TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[38].kind = 2;
NTI_e5YQgQH5C8Fl9cRhRXJezhA_.node = &TM_Y3cCMs4xzyrNE4rsvwdnGQ_0[38];
NTI_RLjzwRut8ihej9aDTKbr77Q_.size = sizeof(tyObject_FileIOError_e5YQgQH5C8Fl9cRhRXJezhA*);
NTI_RLjzwRut8ihej9aDTKbr77Q_.kind = 22;
NTI_RLjzwRut8ihej9aDTKbr77Q_.base = (&NTI_e5YQgQH5C8Fl9cRhRXJezhA_);
NTI_RLjzwRut8ihej9aDTKbr77Q_.marker = Marker_tyRef_RLjzwRut8ihej9aDTKbr77Q;
}

