/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/usr/local/Cellar/nim/0.17.2/nim/lib -o /Users/johnlindsay/Documents/programming/nimCode/wb_denoise/nimcache/stdlib_sequtils.o /Users/johnlindsay/Documents/programming/nimCode/wb_denoise/nimcache/stdlib_sequtils.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_6Ufurnv2NCYPq9bSRr7e5rQ tySequence_6Ufurnv2NCYPq9bSRr7e5rQ;
typedef struct tyObject_Vector3_RMaZxokloMCoinSnTL2X1w tyObject_Vector3_RMaZxokloMCoinSnTL2X1w;
struct TGenericSeq {
NI len;
NI reserved;
};
struct tyObject_Vector3_RMaZxokloMCoinSnTL2X1w {
NF a;
NF b;
NF c;
};
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
struct tySequence_6Ufurnv2NCYPq9bSRr7e5rQ {
  TGenericSeq Sup;
  tyObject_Vector3_RMaZxokloMCoinSnTL2X1w data[SEQ_DECL_SIZE];
};
N_NIMCALL(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, newSeq_QEg0mebvlEuej5bmGcaclQ)(NI len);
N_NIMCALL(tySequence_6Ufurnv2NCYPq9bSRr7e5rQ*, newSeq_vih9bbDDk28KTR0ubeObUoQ)(NI len);

N_NIMCALL(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, repeat_pBHAjECB1SlEt8MwweaBAA)(NF x, NI n) {
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* result;
	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)0;
	result = newSeq_QEg0mebvlEuej5bmGcaclQ(n);
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(((NI) (i_2)) < ((NI) (n)))) goto LA3;
				i = i_2;
				result->data[i] = x;
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}

N_NIMCALL(tySequence_6Ufurnv2NCYPq9bSRr7e5rQ*, repeat_6gkx9aUVkbiN1A9adkuyLMbg)(tyObject_Vector3_RMaZxokloMCoinSnTL2X1w* x, NI n) {
	tySequence_6Ufurnv2NCYPq9bSRr7e5rQ* result;
	result = (tySequence_6Ufurnv2NCYPq9bSRr7e5rQ*)0;
	result = newSeq_vih9bbDDk28KTR0ubeObUoQ(n);
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(((NI) (i_2)) < ((NI) (n)))) goto LA3;
				i = i_2;
				result->data[i] = (*x);
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void) {
}

