/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/usr/local/Cellar/nim/0.17.2/nim/lib -o /Users/johnlindsay/Documents/programming/nimCode/wb_denoise/nimcache/stdlib_posix.o /Users/johnlindsay/Documents/programming/nimCode/wb_denoise/nimcache/stdlib_posix.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
int MAP_POPULATE_VA0iC4AP6fJAacff09cx89ag;
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void) {
	MAP_POPULATE_VA0iC4AP6fJAacff09cx89ag = ((int) 0);
}

NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void) {
}

