/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/usr/local/Cellar/nim/0.17.2/nim/lib -o /Users/johnlindsay/Documents/programming/nimCode/wb_denoise/nimcache/stdlib_unittest.o /Users/johnlindsay/Documents/programming/nimCode/wb_denoise/nimcache/stdlib_unittest.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_2gM6knqz8MaAY9c4MAR2ztg tySequence_2gM6knqz8MaAY9c4MAR2ztg;
typedef struct tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw;
typedef struct RootObj RootObj;
typedef struct tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg;
typedef struct tySequence_4eRCaZmrYLLw2k30GPTiMw tySequence_4eRCaZmrYLLw2k30GPTiMw;
typedef struct tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ;
typedef struct tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw;
typedef struct tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ;
typedef struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyTuple_QeWl6B6ffS4pU6WWrtcrDw tyTuple_QeWl6B6ffS4pU6WWrtcrDw;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct RootObj {
TNimType* m_type;
};
struct tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw {
  RootObj Sup;
};
struct tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg {
tySequence_4eRCaZmrYLLw2k30GPTiMw* data;
NI counter;
};
typedef NU8 tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww;
struct tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw {
  tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw Sup;
NIM_BOOL colorOutput;
tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww outputLevel;
NIM_BOOL isInSuite;
NIM_BOOL isInTest;
};
typedef NU8 tySet_tyEnum_Style_NXKayqTLMsAibFwNceBlpA;
typedef NU8 tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg;
typedef NU8 tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ;
struct tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ {
NimStringDesc* suiteName;
NimStringDesc* testName;
tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ status;
};
struct tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ {
  tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw Sup;
tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* stream;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* testErrors;
NF testStartTime;
NimStringDesc* testStackTrace;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef NU8 tyEnum_FloatFormatMode_pNvEoaqwoxKyoASD11vSgQ;
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
struct tyTuple_QeWl6B6ffS4pU6WWrtcrDw {
NI Field0;
NimStringDesc* Field1;
};
typedef N_NIMCALL_PTR(void, tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_KjFcmLOhf4VQvVcyLJWXZw) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, tyProc_jlOYFw9cHausuCbPoWx2iiA) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, tyProc_tjaJtoUzLe1BMUbItlcGhQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc_b9bsIuILxTLVZHPvJBW187A) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ {
  RootObj Sup;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
tyProc_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
tyProc_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
tyProc_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_2gM6knqz8MaAY9c4MAR2ztg {
  TGenericSeq Sup;
  tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* data[SEQ_DECL_SIZE];
};
struct tySequence_4eRCaZmrYLLw2k30GPTiMw {
  TGenericSeq Sup;
  tyTuple_QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_Um3CQPZ9bILAIolZOsxNIaw_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_NIMCALL(void, Marker_tyRef_po6hYFavJCZm28qf1dR3mw)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence_2gM6knqz8MaAY9c4MAR2ztg)(void* p, NI op);
static N_NIMCALL(void, TM_Um3CQPZ9bILAIolZOsxNIaw_3)(void);
static N_NIMCALL(void, TM_Um3CQPZ9bILAIolZOsxNIaw_4)(void);
N_NIMCALL(NIM_BOOL, existsEnv_vAQ9aK36dVeMFf61ovfHwJw)(NimStringDesc* key);
N_NIMCALL(void, suiteStarted_zvRCVP5x4ZBpPV2Xx9cPHZA)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* suiteName);
N_NIMCALL(void, testStarted_YRuPwQXlDxZko9bSMypk3hA)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName);
N_NIMCALL(void, failureOccurred_Fsq9aCTSjbGiV7TYpR757Lw)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_NIMCALL(void, testEnded_hPRwDS9aOIRJ5MB9buAX30Wg)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult);
N_NIMCALL(void, suiteEnded_RS3dEHKAbuhOugXu1dXVHg)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter);
N_NIMCALL(void, suiteStarted_IXWI0IZVUaexE074PboPzQ)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* suiteName);
N_NIMCALL(void, setStyle_zEKKPPIjKZs9bVYu4TwenLg)(FILE* f, tySet_tyEnum_Style_NXKayqTLMsAibFwNceBlpA style);
N_NIMCALL(void, setForegroundColor_Tw7yxMupneOmAicqiYt3NA)(FILE* f, tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg fg, NIM_BOOL bright);
N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
N_NIMCALL(void, resetAttributes_tFIu39aFSR3N0M64Ynwugng)(FILE* f);
N_NIMCALL(void, testStarted_0WlfvTsMUPRHUfLeuXrGAg)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* testName);
N_NIMCALL(void, failureOccurred_HopmjhtOQil8N9axQ5kNI3w)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, testEnded_AsoOYSa1sGgPTBsUoT9cxsw)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_NIMCALL(void, suiteEnded_IIGQUyJJjT9cNV9c34JPjWGA)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter);
N_NIMCALL(void, suiteStarted_9aAyDoHTMoiLoSiMpkUAFNw)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* suiteName);
N_NIMCALL(void, writeLine_G1TKFmud9akiH9bzSHWMshag)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NimStringDesc** args, NI argsLen_0);
N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_NIMCALL(NimStringDesc*, xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(void, testStarted_EYS8dFM0pZmDNdV9c1cyo4Q)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* testName);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(void, failureOccurred_NAlHeCfOfz1bBvtw2rCPGw)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_NIMCALL(void, add_sp11IzYl5roq19bn4qRQmqA)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ** x, NimStringDesc** y, NI yLen_0);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, testEnded_E5f9a05hVCAPvYslPV2f4TQ)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult);
N_NIMCALL(NimStringDesc*, nsuformatFloat)(NF f, tyEnum_FloatFormatMode_pNvEoaqwoxKyoASD11vSgQ format, NI precision, NIM_CHAR decimalSep);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
N_NIMCALL(void, suiteEnded_EF53BADEiH9a6amiy7eitMg)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter);
NIM_BOOL abortOnError_Bte3Uiwc4Q19ago2N4C89cUA;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
tySequence_2gM6knqz8MaAY9c4MAR2ztg* formatters_55U7g4zhjHV9bCI6emTgDiA;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_dLGU9cWWYqlqOn8lpRVsx9cw_;
TNimType NTI_po6hYFavJCZm28qf1dR3mw_;
TNimType NTI_2gM6knqz8MaAY9c4MAR2ztg_;
tyObject_HashSet_pOhUohTPuRItuGmDY0Ddzg testsToRun_m0XVBZrXPxrhRL0wmi42Iw;
extern TNimType NTI_pOhUohTPuRItuGmDY0Ddzg_;
TNimType NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_kvLOVRX6Za2S0C2QxHXy9cQ_;
extern TNimType NTI_r3Wc5tOoxP8rz1DvGVTUvw_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_dU6QGtP3KgqXg9bZP3nhpWw_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_7UfTrIPsm9cGDPwH9bpwJDww_;
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_5, "NIMTEST_ABORT_ON_ERROR", 22);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_6, "\012[Suite] ", 9);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_7, "\012", 1);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_8, "    ", 4);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_9, "", 0);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_10, "  ", 2);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_11, "[", 1);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_15, "] ", 2);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_16, "\011<testsuite name=\"$1\">", 22);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_17, "&lt;", 4);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_18, "&gt;", 4);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_19, "&amp;", 5);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_20, "&quot;", 6);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_21, "&apos;", 6);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_22, "&#", 2);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_23, "\011\011<testcase name=\"$#\" time=\"$#\">", 32);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_25, "<skipped />", 11);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Um3CQPZ9bILAIolZOsxNIaw_24 = {((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_25)}
;
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_26, "The test failed without outputting an error", 43);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_27, "\011\011\011<error message=\"$#\">$#</error>", 33);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_28, "\011\011\011<system-err>$#</system-err>", 30);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_29, "\011\011\011<failure message=\"$#\">$#</failure>", 37);
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_31, "\011\011</testcase>", 13);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Um3CQPZ9bILAIolZOsxNIaw_30 = {((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_31)}
;
STRING_LITERAL(TM_Um3CQPZ9bILAIolZOsxNIaw_33, "\011</testsuite>", 13);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Um3CQPZ9bILAIolZOsxNIaw_32 = {((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_33)}
;
static N_NIMCALL(void, TM_Um3CQPZ9bILAIolZOsxNIaw_2)(void) {
	nimGCvisit((void*)checkpoints_bq5hLRYOyiTcYy29a9akD9c9bQ, 0);
}
static N_NIMCALL(void, Marker_tyRef_po6hYFavJCZm28qf1dR3mw)(void* p, NI op) {
	tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* a;
	a = (tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw*)p;
}
static N_NIMCALL(void, Marker_tySequence_2gM6knqz8MaAY9c4MAR2ztg)(void* p, NI op) {
	tySequence_2gM6knqz8MaAY9c4MAR2ztg* a;
	NI T1_;
	a = (tySequence_2gM6knqz8MaAY9c4MAR2ztg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, TM_Um3CQPZ9bILAIolZOsxNIaw_3)(void) {
	nimGCvisit((void*)formatters_55U7g4zhjHV9bCI6emTgDiA, 0);
}
static N_NIMCALL(void, TM_Um3CQPZ9bILAIolZOsxNIaw_4)(void) {
	nimGCvisit((void*)testsToRun_m0XVBZrXPxrhRL0wmi42Iw.data, 0);
}

N_NIMCALL(void, suiteStarted_zvRCVP5x4ZBpPV2Xx9cPHZA)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* suiteName) {
}

N_NIMCALL(void, testStarted_YRuPwQXlDxZko9bSMypk3hA)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, NimStringDesc* testName) {
}

N_NIMCALL(void, failureOccurred_Fsq9aCTSjbGiV7TYpR757Lw)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace) {
}

N_NIMCALL(void, testEnded_hPRwDS9aOIRJ5MB9buAX30Wg)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult) {
}

N_NIMCALL(void, suiteEnded_RS3dEHKAbuhOugXu1dXVHg)(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw* formatter) {
}

N_NIMCALL(void, suiteStarted_IXWI0IZVUaexE074PboPzQ)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* suiteName) {
	{
		if (!(*formatter).colorOutput) goto LA3_;
		setStyle_zEKKPPIjKZs9bVYu4TwenLg(stdout, 1);
		setForegroundColor_Tw7yxMupneOmAicqiYt3NA(stdout, ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 34), NIM_FALSE);
		write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_6));
		resetAttributes_tFIu39aFSR3N0M64Ynwugng(stdout);
		write_c4mGyJBvK73pdM22jiweKQ(stdout, suiteName);
		write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_7));
		resetAttributes_tFIu39aFSR3N0M64Ynwugng(stdout);
	}
	goto LA1_;
	LA3_: ;
	{
		printf("%s%s\012", ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_6)? (((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_6))->data:"nil", suiteName? (suiteName)->data:"nil");
		fflush(stdout);
	}
	LA1_: ;
	(*formatter).isInSuite = NIM_TRUE;
}

N_NIMCALL(void, testStarted_0WlfvTsMUPRHUfLeuXrGAg)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, NimStringDesc* testName) {
	(*formatter).isInTest = NIM_TRUE;
}

N_NIMCALL(void, failureOccurred_HopmjhtOQil8N9axQ5kNI3w)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace) {
	NimStringDesc* prefix;
	{
		if (!!((stackTrace == NIM_NIL))) goto LA3_;
		printf("%s\012", stackTrace? (stackTrace)->data:"nil");
		fflush(stdout);
	}
	LA3_: ;
	{
		if (!(*formatter).isInSuite) goto LA7_;
		prefix = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_8));
	}
	goto LA5_;
	LA7_: ;
	{
		prefix = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_9));
	}
	LA5_: ;
	{
		NimStringDesc* msg;
		NI i;
		NI L;
		NI T11_;
		msg = (NimStringDesc*)0;
		i = ((NI) 0);
		T11_ = (checkpoints ? checkpoints->Sup.len : 0);
		L = T11_;
		{
			while (1) {
				if (!(i < L)) goto LA13;
				msg = checkpoints->data[i];
				printf("%s%s\012", prefix? (prefix)->data:"nil", msg? (msg)->data:"nil");
				fflush(stdout);
				i += ((NI) 1);
			} LA13: ;
		}
	}
}

N_NIMCALL(void, testEnded_AsoOYSa1sGgPTBsUoT9cxsw)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult) {
	(*formatter).isInTest = NIM_FALSE;
	{
		NIM_BOOL T3_;
		NIM_BOOL T5_;
		NimStringDesc* prefix;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*formatter).outputLevel == ((tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww) 2)));
		if (!(T3_)) goto LA4_;
		T5_ = (NIM_BOOL)0;
		T5_ = ((*formatter).outputLevel == ((tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww) 0));
		if (T5_) goto LA6_;
		T5_ = ((*testResult).status == ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1));
		LA6_: ;
		T3_ = T5_;
		LA4_: ;
		if (!T3_) goto LA7_;
		{
			if (!!(((*testResult).suiteName == NIM_NIL))) goto LA11_;
			prefix = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_10));
		}
		goto LA9_;
		LA11_: ;
		{
			prefix = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_9));
		}
		LA9_: ;
		{
			NIM_BOOL T16_;
			tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg color;
			T16_ = (NIM_BOOL)0;
			T16_ = (*formatter).colorOutput;
			if (!(T16_)) goto LA17_;
			T16_ = NIM_TRUE;
			LA17_: ;
			if (!T16_) goto LA18_;
			switch ((*testResult).status) {
			case ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 0):
			{
				color = ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 32);
			}
			break;
			case ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1):
			{
				color = ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 31);
			}
			break;
			case ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 2):
			{
				color = ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 33);
			}
			break;
			default:
			{
				color = ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 37);
			}
			break;
			}
			setStyle_zEKKPPIjKZs9bVYu4TwenLg(stdout, 1);
			setForegroundColor_Tw7yxMupneOmAicqiYt3NA(stdout, color, NIM_FALSE);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, prefix);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_11));
			write_c4mGyJBvK73pdM22jiweKQ(stdout, reprEnum((NI)(*testResult).status, (&NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_)));
			write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_15));
			resetAttributes_tFIu39aFSR3N0M64Ynwugng(stdout);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, (*testResult).testName);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_7));
			resetAttributes_tFIu39aFSR3N0M64Ynwugng(stdout);
		}
		goto LA14_;
		LA18_: ;
		{
			printf("%s%s%s%s%s\012", prefix? (prefix)->data:"nil", ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_11)? (((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_11))->data:"nil", reprEnum((NI)(*testResult).status, (&NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_))? (reprEnum((NI)(*testResult).status, (&NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_)))->data:"nil", ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_15)? (((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_15))->data:"nil", (*testResult).testName? ((*testResult).testName)->data:"nil");
			fflush(stdout);
		}
		LA14_: ;
	}
	LA7_: ;
}

N_NIMCALL(void, suiteEnded_IIGQUyJJjT9cNV9c34JPjWGA)(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw* formatter) {
	(*formatter).isInSuite = NIM_FALSE;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(NimStringDesc*, xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ)(NimStringDesc* s) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	result = rawNewString(((NI) ((s ? s->Sup.len : 0))));
	{
		NIM_CHAR c;
		NI i;
		NI L;
		c = (NIM_CHAR)0;
		i = ((NI) 0);
		L = (s ? s->Sup.len : 0);
		{
			while (1) {
				if (!(i < L)) goto LA3;
				c = s->data[i];
				switch (((NU8)(c))) {
				case 60:
				{
					result = resizeString(result, 4);
appendString(result, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_17));
				}
				break;
				case 62:
				{
					result = resizeString(result, 4);
appendString(result, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_18));
				}
				break;
				case 38:
				{
					result = resizeString(result, 5);
appendString(result, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_19));
				}
				break;
				case 34:
				{
					result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_20));
				}
				break;
				case 39:
				{
					result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_21));
				}
				break;
				default:
				{
					{
						NimStringDesc* T14_;
						NimStringDesc* T15_;
						if (!(((NI) (((NU8)(c)))) < ((NI) 32))) goto LA12_;
						T14_ = (NimStringDesc*)0;
						T15_ = (NimStringDesc*)0;
						T15_ = nimIntToStr(((NI) (((NU8)(c)))));
						T14_ = rawNewString(T15_->Sup.len + 3);
appendString(T14_, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_22));
appendString(T14_, T15_);
appendChar(T14_, 59);
						result = resizeString(result, T14_->Sup.len + 0);
appendString(result, T14_);
					}
					goto LA10_;
					LA12_: ;
					{
						result = addChar(result, c);
					}
					LA10_: ;
				}
				break;
				}
				i += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}

N_NIMCALL(void, suiteStarted_9aAyDoHTMoiLoSiMpkUAFNw)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* suiteName) {
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	NimStringDesc* T2_;
	memset((void*)T1_, 0, sizeof(T1_));
	T2_ = (NimStringDesc*)0;
	T2_ = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ(suiteName);
	T1_[0] = nsuFormatSingleElem(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_16), T2_);
	writeLine_G1TKFmud9akiH9bzSHWMshag((*formatter).stream, T1_, 1);
}

N_NIMCALL(void, testStarted_EYS8dFM0pZmDNdV9c1cyo4Q)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, NimStringDesc* testName) {
	(*formatter).testErrors = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) setLengthSeq(&((*formatter).testErrors)->Sup, sizeof(NimStringDesc*), ((NI) 0));
	(*formatter).testStackTrace = setLengthStr((*formatter).testStackTrace, ((NI) 0));
	(*formatter).testStartTime = ntepochTime();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

N_NIMCALL(void, failureOccurred_NAlHeCfOfz1bBvtw2rCPGw)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace) {
	add_sp11IzYl5roq19bn4qRQmqA((&(*formatter).testErrors), checkpoints->data, checkpoints->Sup.len);
	{
		NimStringDesc* T5_;
		if (!!((stackTrace == NIM_NIL))) goto LA3_;
		T5_ = (NimStringDesc*)0;
		T5_ = (*formatter).testStackTrace; (*formatter).testStackTrace = copyStringRC1(stackTrace);
		if (T5_) nimGCunrefNoCycle(T5_);
	}
	LA3_: ;
}

N_NIMCALL(void, testEnded_E5f9a05hVCAPvYslPV2f4TQ)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter, tyObject_TestResult_GEvSVSxdPWWgMGM48ywEYQ* testResult) {
	NF time_1;
	NF T1_;
	NimStringDesc* timeStr;
	tyArray_nHXaesL0DJZHyVS07ARPRA T2_;
	tyArray_Re75IspeoxXy2oCZHwcRrA T3_;
	T1_ = (NF)0;
	T1_ = ntepochTime();
	time_1 = ((NF)(T1_) - (NF)((*formatter).testStartTime));
	timeStr = nsuformatFloat(time_1, ((tyEnum_FloatFormatMode_pNvEoaqwoxKyoASD11vSgQ) 1), ((NI) 8), 46);
	memset((void*)T2_, 0, sizeof(T2_));
	memset((void*)T3_, 0, sizeof(T3_));
	T3_[0] = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ((*testResult).testName);
	T3_[1] = copyString(timeStr);
	T2_[0] = nsuFormatOpenArray(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_23), T3_, 2);
	writeLine_G1TKFmud9akiH9bzSHWMshag((*formatter).stream, T2_, 1);
	switch ((*testResult).status) {
	case ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 0):
	{
	}
	break;
	case ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 2):
	{
		writeLine_G1TKFmud9akiH9bzSHWMshag((*formatter).stream, TM_Um3CQPZ9bILAIolZOsxNIaw_24, 1);
	}
	break;
	case ((tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ) 1):
	{
		NimStringDesc* failureMsg;
		NimStringDesc* errs;
		{
			NIM_BOOL T9_;
			NI T11_;
			NI T14_;
			T9_ = (NIM_BOOL)0;
			T9_ = (((NI) 0) < ((*formatter).testStackTrace ? (*formatter).testStackTrace->Sup.len : 0));
			if (!(T9_)) goto LA10_;
			T11_ = ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0);
			T9_ = (((NI) 0) < T11_);
			LA10_: ;
			if (!T9_) goto LA12_;
			T14_ = ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0);
			failureMsg = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ((*formatter).testErrors->data[(NI)(T14_ - ((NI) 1))]);
		}
		goto LA7_;
		LA12_: ;
		{
			NI T16_;
			T16_ = ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0);
			if (!(((NI) 0) < T16_)) goto LA17_;
			failureMsg = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ((*formatter).testErrors->data[((NI) 0)]);
		}
		goto LA7_;
		LA17_: ;
		{
			failureMsg = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_26));
		}
		LA7_: ;
		errs = copyString(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_9));
		{
			NI T22_;
			NI startIdx;
			NI endIdx;
			T22_ = ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0);
			if (!(((NI) 1) < T22_)) goto LA23_;
			{
				if (!(((NI) 0) < ((*formatter).testStackTrace ? (*formatter).testStackTrace->Sup.len : 0))) goto LA27_;
				startIdx = ((NI) 0);
			}
			goto LA25_;
			LA27_: ;
			{
				startIdx = ((NI) 1);
			}
			LA25_: ;
			{
				NI T34_;
				if (!(((NI) 0) < ((*formatter).testStackTrace ? (*formatter).testStackTrace->Sup.len : 0))) goto LA32_;
				T34_ = ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0);
				endIdx = (NI)(T34_ - ((NI) 2));
			}
			goto LA30_;
			LA32_: ;
			{
				NI T36_;
				T36_ = ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0);
				endIdx = (NI)(T36_ - ((NI) 1));
			}
			LA30_: ;
			{
				NI errIdx;
				NI res;
				errIdx = (NI)0;
				res = startIdx;
				{
					while (1) {
						NimStringDesc* T44_;
						if (!(res <= endIdx)) goto LA39;
						errIdx = res;
						{
							if (!(((NI) 0) < (errs ? errs->Sup.len : 0))) goto LA42_;
							errs = resizeString(errs, 1);
appendString(errs, ((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_7));
						}
						LA42_: ;
						T44_ = (NimStringDesc*)0;
						T44_ = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ((*formatter).testErrors->data[errIdx]);
						errs = resizeString(errs, T44_->Sup.len + 0);
appendString(errs, T44_);
						res += ((NI) 1);
					} LA39: ;
				}
			}
		}
		LA23_: ;
		{
			tyArray_nHXaesL0DJZHyVS07ARPRA T49_;
			tyArray_Re75IspeoxXy2oCZHwcRrA T50_;
			if (!(((NI) 0) < ((*formatter).testStackTrace ? (*formatter).testStackTrace->Sup.len : 0))) goto LA47_;
			memset((void*)T49_, 0, sizeof(T49_));
			memset((void*)T50_, 0, sizeof(T50_));
			T50_[0] = copyString(failureMsg);
			T50_[1] = xmlEscape_kzKyQOwdqPEcJ5FND9bUpFQ((*formatter).testStackTrace);
			T49_[0] = nsuFormatOpenArray(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_27), T50_, 2);
			writeLine_G1TKFmud9akiH9bzSHWMshag((*formatter).stream, T49_, 1);
			{
				tyArray_nHXaesL0DJZHyVS07ARPRA T55_;
				if (!(((NI) 0) < (errs ? errs->Sup.len : 0))) goto LA53_;
				memset((void*)T55_, 0, sizeof(T55_));
				T55_[0] = nsuFormatSingleElem(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_28), errs);
				writeLine_G1TKFmud9akiH9bzSHWMshag((*formatter).stream, T55_, 1);
			}
			LA53_: ;
		}
		goto LA45_;
		LA47_: ;
		{
			tyArray_nHXaesL0DJZHyVS07ARPRA T57_;
			tyArray_Re75IspeoxXy2oCZHwcRrA T58_;
			memset((void*)T57_, 0, sizeof(T57_));
			memset((void*)T58_, 0, sizeof(T58_));
			T58_[0] = copyString(failureMsg);
			T58_[1] = copyString(errs);
			T57_[0] = nsuFormatOpenArray(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_29), T58_, 2);
			writeLine_G1TKFmud9akiH9bzSHWMshag((*formatter).stream, T57_, 1);
		}
		LA45_: ;
	}
	break;
	}
	writeLine_G1TKFmud9akiH9bzSHWMshag((*formatter).stream, TM_Um3CQPZ9bILAIolZOsxNIaw_30, 1);
}

N_NIMCALL(void, suiteEnded_EF53BADEiH9a6amiy7eitMg)(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ* formatter) {
	writeLine_G1TKFmud9akiH9bzSHWMshag((*formatter).stream, TM_Um3CQPZ9bILAIolZOsxNIaw_32, 1);
}
NIM_EXTERNC N_NOINLINE(void, stdlib_unittestInit000)(void) {
nimRegisterGlobalMarker(TM_Um3CQPZ9bILAIolZOsxNIaw_2);
nimRegisterGlobalMarker(TM_Um3CQPZ9bILAIolZOsxNIaw_3);
nimRegisterGlobalMarker(TM_Um3CQPZ9bILAIolZOsxNIaw_4);
	abortOnError_Bte3Uiwc4Q19ago2N4C89cUA = existsEnv_vAQ9aK36dVeMFf61ovfHwJw(((NimStringDesc*) &TM_Um3CQPZ9bILAIolZOsxNIaw_5));
}

NIM_EXTERNC N_NOINLINE(void, stdlib_unittestDatInit000)(void) {
static TNimNode* TM_Um3CQPZ9bILAIolZOsxNIaw_12[3];
NI TM_Um3CQPZ9bILAIolZOsxNIaw_14;
static char* NIM_CONST TM_Um3CQPZ9bILAIolZOsxNIaw_13[3] = {
"OK", 
"FAILED", 
"SKIPPED"};
static TNimNode* TM_Um3CQPZ9bILAIolZOsxNIaw_34[4];
static TNimNode* TM_Um3CQPZ9bILAIolZOsxNIaw_35[4];
static TNimNode* TM_Um3CQPZ9bILAIolZOsxNIaw_36[3];
NI TM_Um3CQPZ9bILAIolZOsxNIaw_38;
static char* NIM_CONST TM_Um3CQPZ9bILAIolZOsxNIaw_37[3] = {
"PRINT_ALL", 
"PRINT_FAILURES", 
"PRINT_NONE"};
static TNimNode TM_Um3CQPZ9bILAIolZOsxNIaw_0[19];
NTI_dLGU9cWWYqlqOn8lpRVsx9cw_.size = sizeof(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw);
NTI_dLGU9cWWYqlqOn8lpRVsx9cw_.kind = 17;
NTI_dLGU9cWWYqlqOn8lpRVsx9cw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_dLGU9cWWYqlqOn8lpRVsx9cw_.flags = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[0].len = 0; TM_Um3CQPZ9bILAIolZOsxNIaw_0[0].kind = 2;
NTI_dLGU9cWWYqlqOn8lpRVsx9cw_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[0];
NTI_po6hYFavJCZm28qf1dR3mw_.size = sizeof(tyObject_OutputFormattercolonObjectType__dLGU9cWWYqlqOn8lpRVsx9cw*);
NTI_po6hYFavJCZm28qf1dR3mw_.kind = 22;
NTI_po6hYFavJCZm28qf1dR3mw_.base = (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_);
NTI_po6hYFavJCZm28qf1dR3mw_.marker = Marker_tyRef_po6hYFavJCZm28qf1dR3mw;
NTI_2gM6knqz8MaAY9c4MAR2ztg_.size = sizeof(tySequence_2gM6knqz8MaAY9c4MAR2ztg*);
NTI_2gM6knqz8MaAY9c4MAR2ztg_.kind = 24;
NTI_2gM6knqz8MaAY9c4MAR2ztg_.base = (&NTI_po6hYFavJCZm28qf1dR3mw_);
NTI_2gM6knqz8MaAY9c4MAR2ztg_.marker = Marker_tySequence_2gM6knqz8MaAY9c4MAR2ztg;
NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_.size = sizeof(tyEnum_TestStatus_W9bTUg9c9a7UlIYkKYmd5uasQ);
NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_.kind = 14;
NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_.base = 0;
NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_.flags = 3;
for (TM_Um3CQPZ9bILAIolZOsxNIaw_14 = 0; TM_Um3CQPZ9bILAIolZOsxNIaw_14 < 3; TM_Um3CQPZ9bILAIolZOsxNIaw_14++) {
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_14+1].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_14+1].offset = TM_Um3CQPZ9bILAIolZOsxNIaw_14;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_14+1].name = TM_Um3CQPZ9bILAIolZOsxNIaw_13[TM_Um3CQPZ9bILAIolZOsxNIaw_14];
TM_Um3CQPZ9bILAIolZOsxNIaw_12[TM_Um3CQPZ9bILAIolZOsxNIaw_14] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_14+1];
}
TM_Um3CQPZ9bILAIolZOsxNIaw_0[4].len = 3; TM_Um3CQPZ9bILAIolZOsxNIaw_0[4].kind = 2; TM_Um3CQPZ9bILAIolZOsxNIaw_0[4].sons = &TM_Um3CQPZ9bILAIolZOsxNIaw_12[0];
NTI_W9bTUg9c9a7UlIYkKYmd5uasQ_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[4];
NTI_kvLOVRX6Za2S0C2QxHXy9cQ_.size = sizeof(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ);
NTI_kvLOVRX6Za2S0C2QxHXy9cQ_.kind = 17;
NTI_kvLOVRX6Za2S0C2QxHXy9cQ_.base = (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_);
TM_Um3CQPZ9bILAIolZOsxNIaw_34[0] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[6];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[6].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[6].offset = offsetof(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ, stream);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[6].typ = (&NTI_r3Wc5tOoxP8rz1DvGVTUvw_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[6].name = "stream";
TM_Um3CQPZ9bILAIolZOsxNIaw_34[1] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[7];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[7].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[7].offset = offsetof(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ, testErrors);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[7].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[7].name = "testErrors";
TM_Um3CQPZ9bILAIolZOsxNIaw_34[2] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[8];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[8].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[8].offset = offsetof(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ, testStartTime);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[8].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[8].name = "testStartTime";
TM_Um3CQPZ9bILAIolZOsxNIaw_34[3] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[9];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[9].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[9].offset = offsetof(tyObject_JUnitOutputFormattercolonObjectType__kvLOVRX6Za2S0C2QxHXy9cQ, testStackTrace);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[9].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[9].name = "testStackTrace";
TM_Um3CQPZ9bILAIolZOsxNIaw_0[5].len = 4; TM_Um3CQPZ9bILAIolZOsxNIaw_0[5].kind = 2; TM_Um3CQPZ9bILAIolZOsxNIaw_0[5].sons = &TM_Um3CQPZ9bILAIolZOsxNIaw_34[0];
NTI_kvLOVRX6Za2S0C2QxHXy9cQ_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[5];
NTI_dU6QGtP3KgqXg9bZP3nhpWw_.size = sizeof(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw);
NTI_dU6QGtP3KgqXg9bZP3nhpWw_.kind = 17;
NTI_dU6QGtP3KgqXg9bZP3nhpWw_.base = (&NTI_dLGU9cWWYqlqOn8lpRVsx9cw_);
NTI_dU6QGtP3KgqXg9bZP3nhpWw_.flags = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_35[0] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[11];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[11].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[11].offset = offsetof(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw, colorOutput);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[11].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[11].name = "colorOutput";
TM_Um3CQPZ9bILAIolZOsxNIaw_35[1] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[12];
NTI_7UfTrIPsm9cGDPwH9bpwJDww_.size = sizeof(tyEnum_OutputLevel_7UfTrIPsm9cGDPwH9bpwJDww);
NTI_7UfTrIPsm9cGDPwH9bpwJDww_.kind = 14;
NTI_7UfTrIPsm9cGDPwH9bpwJDww_.base = 0;
NTI_7UfTrIPsm9cGDPwH9bpwJDww_.flags = 3;
for (TM_Um3CQPZ9bILAIolZOsxNIaw_38 = 0; TM_Um3CQPZ9bILAIolZOsxNIaw_38 < 3; TM_Um3CQPZ9bILAIolZOsxNIaw_38++) {
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_38+13].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_38+13].offset = TM_Um3CQPZ9bILAIolZOsxNIaw_38;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_38+13].name = TM_Um3CQPZ9bILAIolZOsxNIaw_37[TM_Um3CQPZ9bILAIolZOsxNIaw_38];
TM_Um3CQPZ9bILAIolZOsxNIaw_36[TM_Um3CQPZ9bILAIolZOsxNIaw_38] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[TM_Um3CQPZ9bILAIolZOsxNIaw_38+13];
}
TM_Um3CQPZ9bILAIolZOsxNIaw_0[16].len = 3; TM_Um3CQPZ9bILAIolZOsxNIaw_0[16].kind = 2; TM_Um3CQPZ9bILAIolZOsxNIaw_0[16].sons = &TM_Um3CQPZ9bILAIolZOsxNIaw_36[0];
NTI_7UfTrIPsm9cGDPwH9bpwJDww_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[16];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[12].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[12].offset = offsetof(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw, outputLevel);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[12].typ = (&NTI_7UfTrIPsm9cGDPwH9bpwJDww_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[12].name = "outputLevel";
TM_Um3CQPZ9bILAIolZOsxNIaw_35[2] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[17];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[17].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[17].offset = offsetof(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw, isInSuite);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[17].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[17].name = "isInSuite";
TM_Um3CQPZ9bILAIolZOsxNIaw_35[3] = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[18];
TM_Um3CQPZ9bILAIolZOsxNIaw_0[18].kind = 1;
TM_Um3CQPZ9bILAIolZOsxNIaw_0[18].offset = offsetof(tyObject_ConsoleOutputFormattercolonObjectType__dU6QGtP3KgqXg9bZP3nhpWw, isInTest);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[18].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_Um3CQPZ9bILAIolZOsxNIaw_0[18].name = "isInTest";
TM_Um3CQPZ9bILAIolZOsxNIaw_0[10].len = 4; TM_Um3CQPZ9bILAIolZOsxNIaw_0[10].kind = 2; TM_Um3CQPZ9bILAIolZOsxNIaw_0[10].sons = &TM_Um3CQPZ9bILAIolZOsxNIaw_35[0];
NTI_dU6QGtP3KgqXg9bZP3nhpWw_.node = &TM_Um3CQPZ9bILAIolZOsxNIaw_0[10];
}

